namespace Koan.Rag.Abstractions;

/// <summary>
/// Quality evaluation results from running a test set against a corpus.
/// Metrics follow the RAGAS framework supplemented with hallucination and utilization scores.
/// </summary>
public sealed record RagEvaluation
{
    /// <summary>Does the answer follow the retrieved context? (0.0-1.0)</summary>
    public double Faithfulness { get; init; }

    /// <summary>Does the answer address the question? (0.0-1.0)</summary>
    public double AnswerRelevancy { get; init; }

    /// <summary>Are the retrieved chunks relevant to the question? (0.0-1.0)</summary>
    public double ContextPrecision { get; init; }

    /// <summary>Did retrieval find all relevant chunks? (0.0-1.0)</summary>
    public double ContextRecall { get; init; }

    /// <summary>Are there claims not supported by any source? (0.0 = no hallucinations, 1.0 = all hallucinated)</summary>
    public double HallucinationScore { get; init; }

    /// <summary>Fraction of retrieved chunks that contributed to the answer (0.0-1.0)</summary>
    public double ContextUtilization { get; init; }

    /// <summary>Per-test-case results for detailed analysis.</summary>
    public IReadOnlyList<RagTestCaseResult> Results { get; init; } = [];

    /// <summary>Wall-clock time for the full evaluation run.</summary>
    public TimeSpan Duration { get; init; }
}

/// <summary>
/// Result for a single test case within an evaluation run.
/// </summary>
public sealed record RagTestCaseResult
{
    /// <summary>The test case that was evaluated.</summary>
    public required RagTestCase TestCase { get; init; }

    /// <summary>The answer generated by the corpus.</summary>
    public required string GeneratedAnswer { get; init; }

    /// <summary>Source documents used in the answer.</summary>
    public IReadOnlyList<RagSource> Sources { get; init; } = [];

    /// <summary>Per-case faithfulness score.</summary>
    public double Faithfulness { get; init; }

    /// <summary>Per-case answer relevancy score.</summary>
    public double AnswerRelevancy { get; init; }

    /// <summary>Per-case hallucination score.</summary>
    public double HallucinationScore { get; init; }
}

/// <summary>
/// A single test case for RAG evaluation.
/// </summary>
public sealed record RagTestCase(
    string Query,
    string? ExpectedAnswer = null,
    IReadOnlyList<string>? ExpectedSourceIds = null);

/// <summary>
/// A set of test cases for evaluation, loadable from file or built programmatically.
/// </summary>
public sealed class RagTestSet : List<RagTestCase>
{
    /// <summary>Load test cases from a JSON file.</summary>
    public static async Task<RagTestSet> FromJsonFile(string filePath, CancellationToken ct = default)
    {
        await using var stream = File.OpenRead(filePath);
        var cases = await System.Text.Json.JsonSerializer.DeserializeAsync<List<RagTestCase>>(
            stream, cancellationToken: ct);

        var testSet = new RagTestSet();
        if (cases is not null)
            testSet.AddRange(cases);
        return testSet;
    }
}
