# Build
FROM mcr.microsoft.com/dotnet/sdk:10.0.100-rc.1 AS build
WORKDIR /src
COPY . .
RUN dotnet publish ./samples/S12.MedTrials.McpService/S12.MedTrials.McpService.csproj -c Release -o /out

# Run
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /out .
ENV ASPNETCORE_URLS=http://+:5114
EXPOSE 5114
ENTRYPOINT ["dotnet", "S12.MedTrials.McpService.dll"]
