networks:
  Koan_internal:
    internal: true
  Koan_external: {}

services:
  api:
    image: "Koan-s5.recs:dev"
    build:
      context: ../../..
      dockerfile: samples/S5.Recs/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      Koan__Ai__AutoDiscoveryEnabled: "true"
      Koan__Ai__AllowDiscoveryInNonDev: "true"
      Koan_AI_OLLAMA_URLS: "http://ollama:11434"
      Koan__Data__Couchbase__ConnectionString: "couchbase://couchbase"
      Koan__Data__Couchbase__Bucket: "Koan"
      Koan__Data__Weaviate__Endpoint: "http://weaviate:8080"
    ports:
      - "40082:8080"
    depends_on:
      ollama:
        condition: service_healthy
      couchbase:
        condition: service_started
      weaviate:
        condition: service_healthy
    networks:
      - Koan_internal
      - Koan_external
  ollama:
    image: "ollama/ollama:latest"
    volumes:
      - ./Data/ollama:/root/.ollama
    healthcheck:
      test: ["CMD-SHELL", "(curl -fsS http://ollama:11434/api/tags || wget -q -O- http://ollama:11434/api/tags || bash -lc 'exec 3<>/dev/tcp/ollama/11434') >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 12
    networks:
      - Koan_internal
  couchbase:
    image: "public.ecr.aws/docker/library/couchbase:latest"
    volumes:
      - ./Data/couchbase:/opt/couchbase/var
    networks:
      - Koan_internal
  weaviate:
    image: "semitechnologies/weaviate:1.25.6"
    environment:
      QUERY_DEFAULTS_LIMIT: "25"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      CLUSTER_HOSTNAME: "node1"
      RAFT_BOOTSTRAP_EXPECT: "1"
    volumes:
      - ./Data/weaviate:/var/lib/weaviate
    healthcheck:
      test: ["CMD-SHELL", "(curl -fsS http://weaviate:8080/v1/.well-known/ready || wget -q -O- http://weaviate:8080/v1/.well-known/ready || bash -lc 'exec 3<>/dev/tcp/weaviate/8080') >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 12
    networks:
      - Koan_internal
