container_name: vault
image: hashicorp/vault:latest
command: server -dev -dev-listen-address=0.0.0.0:8200
ports:
  - "8200:8200"
environment:
  VAULT_DEV_ROOT_TOKEN_ID: root
cap_add:
  - IPC_LOCK
healthcheck:
  test: ["CMD", "vault", "status"]
  interval: 10s
  timeout: 5s
  retries: 5
restart: unless-stopped
networks:
  - zen-garden
