using Npgsql;
using Koan.Data.Abstractions;
using Koan.Data.Abstractions.Sources;
using Koan.Data.Relational.Orchestration;

namespace Koan.Data.Relational.Npgsql.Runtime;

internal static class NpgsqlSchema
{
    public static async Task Provision<TEntity, TKey>(
        NpgsqlConnection connection,
        NpgsqlEntityPlan<TEntity, TKey> plan,
        NpgsqlRepositoryOptions options,
        CancellationToken ct)
        where TEntity : class, IEntity<TKey>
        where TKey : notnull
    {
        if (await Exists(connection, plan.Schema, plan.Table, ct).ConfigureAwait(false)) return;
        var canCreate = options.SourcePlan.StorageLifecycle == StorageLifecycle.Managed &&
                        options.SourcePlan.Access == DataSourceAccess.ReadWrite &&
                        options.DdlPolicy == RelationalDdlPolicy.AutoCreate;
        if (!canCreate)
            throw new SchemaMismatchException(typeof(TEntity).FullName ?? typeof(TEntity).Name, plan.QualifiedTable,
                options.SourcePlan.StorageLifecycle.ToString(), ["table"], [], ddlAllowed: false);

        // Lifecycle and policy say whether this source may be provisioned at all; they say nothing about
        // where. Automatic DDL issues CREATE against whatever the connection string resolves to, which in
        // production is live data, so the environment is a separate question with a separate answer
        // (DATA-0119, ARCH-0128). The consent value was carried this far all along and never read.
        if (!RelationalDdlGate.Allowed(options.AllowProductionDdl))
            throw new InvalidOperationException(
                $"PostgreSQL cannot provision '{plan.QualifiedTable}'. {RelationalDdlGate.Refusal}");

        await using var command = connection.CreateCommand();
        command.CommandText = CreateSql(plan);
        await command.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
    }

    public static async Task Validate<TEntity, TKey>(
        NpgsqlConnection connection,
        NpgsqlEntityPlan<TEntity, TKey> plan,
        NpgsqlRepositoryOptions options,
        CancellationToken ct)
        where TEntity : class, IEntity<TKey>
        where TKey : notnull
    {
        if (!await Exists(connection, plan.Schema, plan.Table, ct).ConfigureAwait(false))
            throw new SchemaMismatchException(typeof(TEntity).FullName ?? typeof(TEntity).Name, plan.QualifiedTable,
                options.SourcePlan.StorageLifecycle.ToString(), ["table"], [],
                options.SourcePlan.StorageLifecycle == StorageLifecycle.Managed);
    }

    public static async Task<bool> Exists(NpgsqlConnection connection, string schema, string table, CancellationToken ct)
    {
        await using var command = connection.CreateCommand();
        command.CommandText = "SELECT 1 FROM information_schema.tables WHERE table_schema = @schema AND table_name = @table";
        command.Parameters.AddWithValue("schema", schema);
        command.Parameters.AddWithValue("table", table);
        return await command.ExecuteScalarAsync(ct).ConfigureAwait(false) is not null;
    }

    private static string CreateSql<TEntity, TKey>(NpgsqlEntityPlan<TEntity, TKey> plan)
        where TEntity : class, IEntity<TKey>
        where TKey : notnull
    {
        var roots = plan.Mapping.Bindings.GroupBy(static binding => binding.PhysicalPath.Name, StringComparer.Ordinal);
        var definitions = new List<string>();
        foreach (var root in roots)
        {
            var identity = root.FirstOrDefault(binding => plan.Mapping.Identity.Parts.Any(part => part.Id == binding.Id));
            var structured = root.Any(binding => binding.Shape == MappingValueShape.Object || binding.PhysicalPath.IsNested);
            var type = structured ? "jsonb" : StoreType((identity ?? root.First()).PhysicalType);
            var generated = identity?.Descriptor.Generation == MappingGeneration.Provider
                ? " GENERATED BY DEFAULT AS IDENTITY"
                : string.Empty;
            definitions.Add($"{NpgsqlDialect.Quote(root.Key)} {type}{generated} NOT NULL");
        }
        definitions.Add($"PRIMARY KEY ({string.Join(", ", plan.IdentityRoots.Select(NpgsqlDialect.Quote))})");
        return $"CREATE SCHEMA IF NOT EXISTS {NpgsqlDialect.Quote(plan.Schema)}; " +
               $"CREATE TABLE IF NOT EXISTS {plan.QualifiedTable} ({string.Join(", ", definitions)})";
    }

    private static string StoreType(Type type)
    {
        var value = Nullable.GetUnderlyingType(type) ?? type;
        if (value.IsEnum) value = Enum.GetUnderlyingType(value);
        if (value == typeof(short) || value == typeof(byte) || value == typeof(sbyte)) return "smallint";
        if (value == typeof(int) || value == typeof(ushort)) return "integer";
        if (value == typeof(long) || value == typeof(uint)) return "bigint";
        if (value == typeof(bool)) return "boolean";
        if (value == typeof(decimal)) return "numeric";
        if (value == typeof(float)) return "real";
        if (value == typeof(double)) return "double precision";
        if (value == typeof(Guid)) return "uuid";
        if (value == typeof(DateTime)) return "timestamp";
        if (value == typeof(DateTimeOffset)) return "timestamptz";
        if (value == typeof(DateOnly)) return "date";
        if (value == typeof(TimeOnly)) return "time";
        if (value == typeof(TimeSpan)) return "interval";
        if (value == typeof(byte[])) return "bytea";
        return "text";
    }
}
