using Koan.Data.Relational.Orchestration;
using Npgsql;

namespace Koan.Data.Relational.Npgsql.Runtime;

/// <summary>
/// How a PostgreSQL-wire store spells a schema, a table and a column. Every decision behind these words belongs
/// to the schema orchestrator; this speaks over a connection the repository has already opened, for one schema
/// operation. Connecting here creates nothing, so the repository can open before consent is settled.
/// </summary>
internal sealed class NpgsqlDdlExecutor(NpgsqlConnection connection) : IRelationalDdlExecutor
{
    public async Task<RelationalTableShape?> Describe(RelationalTableDefinition table, CancellationToken ct = default)
    {
        await using var command = connection.CreateCommand();
        command.CommandText = """
            SELECT c.column_name, k.ordinal_position
              FROM information_schema.columns AS c
              LEFT JOIN information_schema.table_constraints AS t
                ON t.table_schema = c.table_schema
               AND t.table_name = c.table_name
               AND t.constraint_type = 'PRIMARY KEY'
              LEFT JOIN information_schema.key_column_usage AS k
                ON k.constraint_name = t.constraint_name
               AND k.table_schema = c.table_schema
               AND k.table_name = c.table_name
               AND k.column_name = c.column_name
             WHERE c.table_schema = @schema AND c.table_name = @table
             ORDER BY c.ordinal_position
            """;
        command.Parameters.AddWithValue("schema", table.Schema);
        command.Parameters.AddWithValue("table", table.Name);

        var columns = new Dictionary<string, RelationalColumnState?>(StringComparer.OrdinalIgnoreCase);
        var key = new List<(int Ordinal, string Name)>();
        await using (var reader = await command.ExecuteReaderAsync(ct).ConfigureAwait(false))
        {
            while (await reader.ReadAsync(ct).ConfigureAwait(false))
            {
                var name = reader.GetString(0);
                // Presence only. This runtime has never compared column definitions, and starting to would judge
                // every existing database against expectations no release has ever held it to; that is a
                // capability of its own, with its own proof, not a side effect of moving the decision.
                columns[name] = null;
                if (!reader.IsDBNull(1)) key.Add((reader.GetInt32(1), name));
            }
        }

        return columns.Count == 0
            ? null
            : new RelationalTableShape(
                columns,
                key.OrderBy(static part => part.Ordinal).Select(static part => part.Name).ToArray());
    }

    public Task Create(RelationalTableDefinition table, CancellationToken ct = default)
    {
        var definitions = table.Columns
            .Select(column => $"{NpgsqlDialect.Quote(column.Name)} {StoreType(column)}" +
                              (column.IsIdentity && column.IsGenerated ? " GENERATED BY DEFAULT AS IDENTITY" : string.Empty) +
                              " NOT NULL")
            .ToList();
        definitions.Add($"PRIMARY KEY ({string.Join(", ", table.Identity.Select(NpgsqlDialect.Quote))})");
        return Execute(
            $"CREATE SCHEMA IF NOT EXISTS {NpgsqlDialect.Quote(table.Schema)}; " +
            $"CREATE TABLE IF NOT EXISTS {Qualify(table)} ({string.Join(", ", definitions)})",
            ct);
    }

    public Task AddColumn(RelationalTableDefinition table, RelationalColumnDefinition column, CancellationToken ct = default) =>
        // Never NOT NULL: a populated table rejects one without a default, and the only columns this store
        // declares NOT NULL arrive with the table itself.
        Execute(
            $"ALTER TABLE {Qualify(table)} " +
            $"ADD COLUMN IF NOT EXISTS {NpgsqlDialect.Quote(column.Name)} {StoreType(column)}",
            ct);

    private async Task Execute(string sql, CancellationToken ct)
    {
        await using var command = connection.CreateCommand();
        command.CommandText = sql;
        await command.ExecuteNonQueryAsync(ct).ConfigureAwait(false);
    }

    private static string Qualify(RelationalTableDefinition table) =>
        $"{NpgsqlDialect.Quote(table.Schema)}.{NpgsqlDialect.Quote(table.Name)}";

    private static string StoreType(RelationalColumnDefinition column)
    {
        if (column.Shape == RelationalStorageShape.Structured) return "jsonb";
        var value = Nullable.GetUnderlyingType(column.ClrType) ?? column.ClrType;
        if (value.IsEnum) value = Enum.GetUnderlyingType(value);
        if (value == typeof(short) || value == typeof(byte) || value == typeof(sbyte)) return "smallint";
        if (value == typeof(int) || value == typeof(ushort)) return "integer";
        if (value == typeof(long) || value == typeof(uint)) return "bigint";
        if (value == typeof(bool)) return "boolean";
        if (value == typeof(decimal)) return "numeric";
        if (value == typeof(float)) return "real";
        if (value == typeof(double)) return "double precision";
        if (value == typeof(Guid)) return "uuid";
        if (value == typeof(DateTime)) return "timestamp";
        if (value == typeof(DateTimeOffset)) return "timestamptz";
        if (value == typeof(DateOnly)) return "date";
        if (value == typeof(TimeOnly)) return "time";
        if (value == typeof(TimeSpan)) return "interval";
        if (value == typeof(byte[])) return "bytea";
        return "text";
    }
}
