namespace Koan.Rag.Abstractions;

/// <summary>
/// Quality evaluation results from running a test set against a corpus.
/// Metrics follow the RAGAS framework supplemented with hallucination and utilization scores.
/// </summary>
public sealed record RagEvaluation
{
    /// <summary>Does the answer follow the retrieved context? (0.0-1.0)</summary>
    public double Faithfulness { get; init; }

    /// <summary>Does the answer address the question? (0.0-1.0)</summary>
    public double AnswerRelevancy { get; init; }

    /// <summary>Are the retrieved chunks relevant to the question? (0.0-1.0)</summary>
    public double ContextPrecision { get; init; }

    /// <summary>Did retrieval find all relevant chunks? (0.0-1.0)</summary>
    public double ContextRecall { get; init; }

    /// <summary>Are there claims not supported by any source? (0.0 = no hallucinations, 1.0 = all hallucinated)</summary>
    public double HallucinationScore { get; init; }

    /// <summary>Fraction of retrieved chunks that contributed to the answer (0.0-1.0)</summary>
    public double ContextUtilization { get; init; }

    /// <summary>Per-test-case results for detailed analysis.</summary>
    public IReadOnlyList<RagTestCaseResult> Results { get; init; } = [];

    /// <summary>Wall-clock time for the full evaluation run.</summary>
    public TimeSpan Duration { get; init; }
}

/// <summary>
/// Result for a single test case within an evaluation run.
/// </summary>
public sealed record RagTestCaseResult
{
    /// <summary>The test case that was evaluated.</summary>
    public required RagTestCase TestCase { get; init; }

    /// <summary>The answer generated by the corpus.</summary>
    public required string GeneratedAnswer { get; init; }

    /// <summary>Source documents used in the answer.</summary>
    public IReadOnlyList<RagSource> Sources { get; init; } = [];

    /// <summary>Per-case faithfulness score.</summary>
    public double Faithfulness { get; init; }

    /// <summary>Per-case answer relevancy score.</summary>
    public double AnswerRelevancy { get; init; }

    /// <summary>Per-case hallucination score.</summary>
    public double HallucinationScore { get; init; }
}

/// <summary>
/// A single test case for RAG evaluation.
/// </summary>
public sealed record RagTestCase(
    string Query,
    string? ExpectedAnswer = null,
    IReadOnlyList<string>? ExpectedSourceIds = null);

/// <summary>
/// A set of test cases for evaluation, built programmatically or loaded via
/// <c>RagTestSetLoader</c> in <c>Koan.Rag</c>.
/// </summary>
public sealed class RagTestSet
{
    private readonly List<RagTestCase> _cases = [];

    /// <summary>All test cases in this set.</summary>
    public IReadOnlyList<RagTestCase> Cases => _cases;

    /// <summary>Number of test cases.</summary>
    public int Count => _cases.Count;

    /// <summary>Add a single test case.</summary>
    public void Add(RagTestCase testCase) => _cases.Add(testCase);

    /// <summary>Add multiple test cases.</summary>
    public void AddRange(IEnumerable<RagTestCase> testCases) => _cases.AddRange(testCases);

    /// <summary>Enumerate test cases.</summary>
    public IEnumerator<RagTestCase> GetEnumerator() => _cases.GetEnumerator();
}
