param(
    [string]$BaseUrl = "http://localhost:5080",
    [switch]$SkipCertificateCheck,
    [string]$OutputDirectory = ""
)

$scriptRoot = Split-Path -Parent $PSCommandPath
. (Join-Path $scriptRoot 'phase4.5-common.ps1')

if ([string]::IsNullOrWhiteSpace($OutputDirectory)) {
    $OutputDirectory = Join-Path $scriptRoot 'output'
}

New-Item -ItemType Directory -Path $OutputDirectory -Force | Out-Null

Write-Host "Scenario A - Enterprise Architecture Review" -ForegroundColor Cyan
Write-Host "Base URL: $BaseUrl" -ForegroundColor DarkGray

$sourcePrompts = @(
    @{
        Prompt = "Meeting notes focusing on enterprise architecture discussions, decisions, and action items.";
        Tags = @("meeting","architecture","notes");
        DescriptorHints = @(
            "enterprise architecture steering committee notes",
            "action items for modernization initiatives",
            "architecture decisions and follow-ups"
        );
        SignalPhrases = @(
            "architecture steering committee",
            "action item",
            "integration gateway",
            "sandbox credentials"
        )
    },
    @{
        Prompt = "Customer technical bulletin summarizing product updates and integration highlights for clients.";
        Tags = @("customer","bulletin","update");
        DescriptorHints = @(
            "customer technical bulletin",
            "product update summary",
            "integration highlights"
        );
        SignalPhrases = @(
            "technical bulletin",
            "early access program",
            "integration playbook",
            "webinar series"
        )
    },
    @{
        Prompt = "Vendor prescreen questionnaire responses describing revenue figures, staffing levels, certifications, and capabilities.";
        Tags = @("vendor","questionnaire","finance");
        DescriptorHints = @(
            "vendor prescreen questionnaire",
            "capability assessment questionnaire",
            "vendor revenue disclosures"
        );
        SignalPhrases = @(
            "FY2024 revenue",
            "staffing count",
            "differentiators",
            "certification"
        )
    },
    @{
        Prompt = "Cybersecurity risk assessment summarizing current controls, findings, and remediation guidance.";
        Tags = @("security","assessment","risk");
        DescriptorHints = @(
            "cybersecurity risk assessment",
            "security posture assessment",
            "remediation guidance summary"
        );
        SignalPhrases = @(
            "zero trust",
            "log retention",
            "quarterly security review",
            "risk assessment"
        )
    }
)

$sourceTypes = @()
foreach ($entry in $sourcePrompts) {
    $created = Ensure-MeridianSourceTypeAi -BaseUrl $BaseUrl -Prompt $entry.Prompt -TargetFields $entry.TargetFields -DesiredTags $entry.Tags -FallbackDescriptorHints $entry.DescriptorHints -FallbackSignalPhrases $entry.SignalPhrases -SkipCertificateCheck:$SkipCertificateCheck
    $sourceTypes += $created
    $sourceName = Get-Property -Object $created -Names 'Name','name'
    $sourceId = Get-Property -Object $created -Names 'Id','id'
    Write-Host "Source type ready: $sourceName ($sourceId)" -ForegroundColor DarkGray
}

$sourceTypeIds = $sourceTypes | ForEach-Object { Get-Property -Object $_ -Names 'Id','id' }

$analysis = Ensure-MeridianAnalysisTypeAi -BaseUrl $BaseUrl -Goal "Produce an enterprise architecture readiness review synthesizing meeting notes, customer bulletins, vendor questionnaires, and cybersecurity assessments." -Audience "CIO steering committee" -IncludedSourceTypes $sourceTypeIds -AdditionalContext "Emphasize key findings, financial health, staffing, and security posture. Use concise markdown sections." -SkipCertificateCheck:$SkipCertificateCheck
$analysisId = Get-Property -Object $analysis -Names 'Id','id'
$analysisName = Get-Property -Object $analysis -Names 'Name','name'
Write-Host "Analysis type ready: $analysisName ($analysisId)" -ForegroundColor DarkGray

# Pipeline definition - schema and template come from AnalysisType automatically via hook
$pipelineDefinition = [ordered]@{
    Name             = "Enterprise Architecture Review " + (Get-Date -Format 'yyyyMMdd-HHmmss')
    Description      = "Pipeline generated by Scenario A script"
    AnalysisTypeId   = $analysisId
}

$pipeline = New-MeridianPipeline -BaseUrl $BaseUrl -Definition $pipelineDefinition -SkipCertificateCheck:$SkipCertificateCheck
$pipelineId = Get-Property -Object $pipeline -Names 'Id','id'
Write-Host "Pipeline created: $pipelineId" -ForegroundColor DarkGray

$documents = @(
    @{ FileName = "meeting-notes.txt"; Content = @"
Arcadia Systems Architecture Steering Committee - 2025-10-20
Attendees: CIO Dana Wright, Lead Architect Leo Martinez, Vendor Liaison Priya Shah.
Agenda focused on the Atlas modernization initiative and partner selection timeline.
Key discussion: Synapse Analytics committed to piloting the integration gateway by 2025-11-15.
Action: Infrastructure team (owner: Morgan Ellis) to prepare sandbox credentials for Synapse by next Monday.
"@.Trim() },
    @{ FileName = "customer-bulletin.txt"; Content = @"
Customer Technical Bulletin - October 2025
Arcadia Systems announces Atlas 4.2 with expanded telemetry sharing and a guided onboarding assistant.
Highlights:
- Early access program opens 2025-11-01 for retail clients.
- Dedicated success engineer Camila Torres assigned to top-tier customers.
- Webinar series scheduled with regional partner NovaBridge to demonstrate integration playbooks.
"@.Trim() },
    @{ FileName = "vendor-prescreen.txt"; Content = @"
Vendor Prescreen Questionnaire - Synapse Analytics
Primary contact: Jordan Kim (Director of Enterprise Accounts).
Financial snapshot: FY2024 revenue reported as 47.2 million USD; staffing count 150 (with 35 engineers assigned to Arcadia engagements).
Differentiators: ISO 27001 certification, 24/7 support desk, regional data residency in NA and EU.
Requested references: Northwind Co., BlueRidge Health.
"@.Trim() },
    @{ FileName = "cybersecurity-assessment.txt"; Content = @"
Cybersecurity Risk Assessment - Synapse Analytics
Conducted by Arcadia Security Office lead Priya Shah on 2025-10-18.
Observations:
- Zero trust network segmentation implemented; SOC 2 Type II in place.
- Minor finding: log retention policy currently 10 months (Arcadia standard requires 12); remediation planned by 2025-12-31.
- No evidence of critical vulnerabilities across portal or API endpoints.
Conclusion: Approved for controlled production rollout with quarterly security reviews.
"@.Trim() }
)

$jobs = @()
foreach ($doc in $documents) {
    $upload = Upload-MeridianDocumentContent -BaseUrl $BaseUrl -PipelineId $pipelineId -FileName $doc.FileName -Content $doc.Content -SkipCertificateCheck:$SkipCertificateCheck
    $jobId = Get-Property -Object $upload -Names 'JobId','jobId'
    if ($jobId) {
        $job = Wait-MeridianJob -BaseUrl $BaseUrl -PipelineId $pipelineId -JobId $jobId -SkipCertificateCheck:$SkipCertificateCheck
        $jobs += $job
    }
}

$deliverable = Get-MeridianDeliverable -BaseUrl $BaseUrl -PipelineId $pipelineId -SkipCertificateCheck:$SkipCertificateCheck
if ($deliverable) {
    $outputPath = Join-Path $OutputDirectory ("scenario-a-deliverable-" + (Get-Date -Format 'yyyyMMdd-HHmmss') + ".md")
    $markdown = Get-Property -Object $deliverable -Names 'RenderedMarkdown','renderedMarkdown','Markdown','markdown'
    if ($markdown) {
        [System.IO.File]::WriteAllText($outputPath, $markdown)
        Write-Host "Deliverable saved to $outputPath" -ForegroundColor Green
    } else {
        Write-Warning "Deliverable has no markdown content."
    }
} else {
    Write-Warning "No deliverable was generated."
}

Write-Host "Scenario A complete. Pipeline: $pipelineId" -ForegroundColor Cyan
