param(
    [string]$BaseUrl = "http://localhost:5080",
    [switch]$SkipCertificateCheck,
    [string]$OutputDirectory = ""
)

$scriptRoot = Split-Path -Parent $PSCommandPath
. (Join-Path $scriptRoot 'phase4.5-common.ps1')

if ([string]::IsNullOrWhiteSpace($OutputDirectory)) {
    $OutputDirectory = Join-Path $scriptRoot 'output'
}

New-Item -ItemType Directory -Path $OutputDirectory -Force | Out-Null

Write-Host "Scenario D - Override Persistence Through Refresh" -ForegroundColor Cyan
Write-Host "Base URL: $BaseUrl" -ForegroundColor DarkGray

$sourcePrompts = @(
    @{ Prompt = "Meeting notes capturing enterprise architecture discussions and vendor evaluation decisions."; Tags = @("meeting","architecture"); TargetFields = @("$.notes") },
    @{ Prompt = "Vendor questionnaire responses describing revenue, staffing, certifications, and service offerings."; Tags = @("vendor","finance"); TargetFields = @("$.revenue","$.employees") }
)

$sourceTypes = @()
foreach ($entry in $sourcePrompts) {
    $created = Ensure-MeridianSourceTypeAi -BaseUrl $BaseUrl -Prompt $entry.Prompt -TargetFields $entry.TargetFields -DesiredTags $entry.Tags -SkipCertificateCheck:$SkipCertificateCheck
    $sourceTypes += $created
    $sourceName = Get-Property -Object $created -Names 'Name','name'
    $sourceId = Get-Property -Object $created -Names 'Id','id'
    Write-Host "Source type ready: $sourceName ($sourceId)" -ForegroundColor DarkGray
}

$sourceTypeIds = $sourceTypes | ForEach-Object { Get-Property -Object $_ -Names 'Id','id' }

$analysis = Ensure-MeridianAnalysisTypeAi -BaseUrl $BaseUrl -Goal "Summarize vendor readiness with emphasis on financial accuracy and staffing." -Audience "Architecture steering committee" -IncludedSourceTypes $sourceTypeIds -AdditionalContext "Ensure markdown highlights revenue and employees with override notes if present." -SkipCertificateCheck:$SkipCertificateCheck
$analysisId = Get-Property -Object $analysis -Names 'Id','id'
$analysisTemplate = Get-Property -Object $analysis -Names 'OutputTemplate','outputTemplate','TemplateMarkdown','templateMarkdown'
Write-Host "Analysis type ready: $(Get-Property -Object $analysis -Names 'Name','name') ($analysisId)" -ForegroundColor DarkGray

$schemaJson = @"
{
  "type": "object",
  "properties": {
    "revenue": { "type": "number" },
    "employees": { "type": "number" }
  }
}
"@

$pipelineDefinition = [ordered]@{
    Name             = "Override Persistence Pipeline " + (Get-Date -Format 'yyyyMMdd-HHmmss')
    Description      = "Pipeline generated by Scenario D"
    AnalysisTypeId   = $analysisId
    SchemaJson       = $schemaJson
    TemplateMarkdown = if ($analysisTemplate) { $analysisTemplate } else { "# Vendor Summary`nRevenue: {{revenue}}`nEmployees: {{employees}}" }
}

$pipeline = New-MeridianPipeline -BaseUrl $BaseUrl -Definition $pipelineDefinition -SkipCertificateCheck:$SkipCertificateCheck
$pipelineId = Get-Property -Object $pipeline -Names 'Id','id'
Write-Host "Pipeline created: $pipelineId" -ForegroundColor DarkGray

$baselineDocs = @(
    @{ FileName = "meeting-baseline.txt"; Content = "Architecture steering meeting notes capturing vendor evaluation outcomes." },
    @{ FileName = "vendor-baseline.txt"; Content = "Vendor questionnaire baseline: revenue 47.2 million USD; employees 150." }
)

foreach ($doc in $baselineDocs) {
    $upload = Upload-MeridianDocumentContent -BaseUrl $BaseUrl -PipelineId $pipelineId -FileName $doc.FileName -Content $doc.Content -SkipCertificateCheck:$SkipCertificateCheck
    $jobId = Get-Property -Object $upload -Names 'JobId','jobId'
    if ($jobId) {
        Wait-MeridianJob -BaseUrl $BaseUrl -PipelineId $pipelineId -JobId $jobId -SkipCertificateCheck:$SkipCertificateCheck | Out-Null
    }
}

$encodedField = [System.Uri]::EscapeDataString('$.revenue')
$overrideRequest = @{ value = 52.5; reason = "Finance override for audited value"; reviewer = "scenario-d" }
Invoke-MeridianRequest -BaseUrl $BaseUrl -Path "/api/pipelines/$pipelineId/fields/$encodedField/override" -Method 'POST' -Body $overrideRequest -SkipCertificateCheck:$SkipCertificateCheck | Out-Null

Write-Host "Uploading updated vendor addendum while override is active..." -ForegroundColor DarkGray
$updateUpload = Upload-MeridianDocumentContent -BaseUrl $BaseUrl -PipelineId $pipelineId -FileName 'vendor-addendum.txt' -Content "Vendor addendum announcing provisional revenue projection of 55.0 million USD." -SkipCertificateCheck:$SkipCertificateCheck
$updateJobId = Get-Property -Object $updateUpload -Names 'JobId','jobId'
if ($updateJobId) {
    Wait-MeridianJob -BaseUrl $BaseUrl -PipelineId $pipelineId -JobId $updateJobId -SkipCertificateCheck:$SkipCertificateCheck | Out-Null
}

$refreshResponse = Invoke-MeridianRequest -BaseUrl $BaseUrl -Path "/api/pipelines/$pipelineId/refresh" -Method 'POST' -SkipCertificateCheck:$SkipCertificateCheck
$refreshJobId = Get-Property -Object $refreshResponse -Names 'JobId','jobId'
if ($refreshJobId) {
    Wait-MeridianJob -BaseUrl $BaseUrl -PipelineId $pipelineId -JobId $refreshJobId -SkipCertificateCheck:$SkipCertificateCheck | Out-Null
}

$deliverable = Get-MeridianDeliverable -BaseUrl $BaseUrl -PipelineId $pipelineId -SkipCertificateCheck:$SkipCertificateCheck
if ($deliverable) {
    $outputPath = Join-Path $OutputDirectory ("scenario-d-override-persisted-" + (Get-Date -Format 'yyyyMMdd-HHmmss') + ".md")
    [System.IO.File]::WriteAllText($outputPath, $deliverable.Markdown)
    Write-Host "Deliverable with override persistence saved to $outputPath" -ForegroundColor Green
    if ($deliverable.Markdown -notmatch "52.5") {
        Write-Warning "Override value did not appear in the deliverable. Review manually."
    }
} else {
    Write-Warning "Deliverable not available after refresh."        
}

Write-Host "Scenario D complete. Override remained in place during refresh." -ForegroundColor Cyan
