param(
    [string]$BaseUrl = "http://localhost:5080",
    [switch]$SkipCertificateCheck,
    [string]$OutputDirectory = ""
)

$scriptRoot = Split-Path -Parent $PSCommandPath
. (Join-Path $scriptRoot 'phase4.5-common.ps1')

if ([string]::IsNullOrWhiteSpace($OutputDirectory)) {
    $OutputDirectory = Join-Path $scriptRoot 'output'
}

New-Item -ItemType Directory -Path $OutputDirectory -Force | Out-Null

Write-Host "Scenario C - Targeted Incremental Refresh" -ForegroundColor Cyan
Write-Host "Base URL: $BaseUrl" -ForegroundColor DarkGray

$sourcePrompts = @(
    @{ Prompt = "Vendor questionnaire responses capturing revenue, staffing, certifications, and capabilities."; Tags = @("vendor","finance"); TargetFields = @("$.revenue","$.employees") },
    @{ Prompt = "Architecture meeting notes describing follow-up actions for vendor evaluation."; Tags = @("meeting","architecture"); TargetFields = @("$.notes") }
)

$sourceTypes = @()
foreach ($entry in $sourcePrompts) {
    $created = Ensure-MeridianSourceTypeAi -BaseUrl $BaseUrl -Prompt $entry.Prompt -TargetFields $entry.TargetFields -DesiredTags $entry.Tags -SkipCertificateCheck:$SkipCertificateCheck
    $sourceTypes += $created
    $sourceName = Get-Property -Object $created -Names 'Name','name'
    $sourceId = Get-Property -Object $created -Names 'Id','id'
    Write-Host "Source type ready: $sourceName ($sourceId)" -ForegroundColor DarkGray
}

$sourceTypeIds = $sourceTypes | ForEach-Object { Get-Property -Object $_ -Names 'Id','id' }

$analysis = Ensure-MeridianAnalysisTypeAi -BaseUrl $BaseUrl -Goal "Produce a vendor financial summary with staffing insight." -Audience "Architecture finance reviewers" -IncludedSourceTypes $sourceTypeIds -AdditionalContext "Highlight any changes between uploads and keep markdown concise." -SkipCertificateCheck:$SkipCertificateCheck
$analysisId = Get-Property -Object $analysis -Names 'Id','id'
$analysisTemplate = Get-Property -Object $analysis -Names 'OutputTemplate','outputTemplate','TemplateMarkdown','templateMarkdown'
Write-Host "Analysis type ready: $(Get-Property -Object $analysis -Names 'Name','name') ($analysisId)" -ForegroundColor DarkGray

$schemaJson = @"
{
  "type": "object",
  "properties": {
    "revenue": { "type": "number" },
    "employees": { "type": "number" },
    "notes": { "type": "string" }
  }
}
"@

$pipelineDefinition = [ordered]@{
    Name             = "Incremental Refresh Pipeline " + (Get-Date -Format 'yyyyMMdd-HHmmss')
    Description      = "Pipeline generated by Scenario C"
    AnalysisTypeId   = $analysisId
    SchemaJson       = $schemaJson
    TemplateMarkdown = if ($analysisTemplate) { $analysisTemplate } else { "# Vendor Summary`nRevenue: {{revenue}}`nEmployees: {{employees}}`nNotes: {{notes}}" }
}

$pipeline = New-MeridianPipeline -BaseUrl $BaseUrl -Definition $pipelineDefinition -SkipCertificateCheck:$SkipCertificateCheck
$pipelineId = Get-Property -Object $pipeline -Names 'Id','id'
Write-Host "Pipeline created: $pipelineId" -ForegroundColor DarkGray

$baselineDocuments = @(
    @{ FileName = "vendor-baseline.txt"; Content = "Vendor questionnaire baseline: revenue 47.2 million USD; employees 150." },
    @{ FileName = "meeting-baseline.txt"; Content = "Meeting notes baseline capturing vendor evaluation discussions." }
)

foreach ($doc in $baselineDocuments) {
    $upload = Upload-MeridianDocumentContent -BaseUrl $BaseUrl -PipelineId $pipelineId -FileName $doc.FileName -Content $doc.Content -SkipCertificateCheck:$SkipCertificateCheck
    $jobId = Get-Property -Object $upload -Names 'JobId','jobId'
    if ($jobId) {
        Wait-MeridianJob -BaseUrl $BaseUrl -PipelineId $pipelineId -JobId $jobId -SkipCertificateCheck:$SkipCertificateCheck | Out-Null
    }
}

$initialDeliverable = Get-MeridianDeliverable -BaseUrl $BaseUrl -PipelineId $pipelineId -SkipCertificateCheck:$SkipCertificateCheck
if ($initialDeliverable) {
    $path = Join-Path $OutputDirectory ("scenario-c-baseline-" + (Get-Date -Format 'yyyyMMdd-HHmmss') + ".md")
    [System.IO.File]::WriteAllText($path, $initialDeliverable.Markdown)
    Write-Host "Baseline deliverable saved to $path" -ForegroundColor Green
}

Write-Host "Uploading targeted update document..." -ForegroundColor DarkGray
$updateDoc = @{ FileName = "vendor-update.txt"; Content = "Vendor addendum: projected revenue raised to 51.5 million USD with staffing plan for 165 employees." }
$uploadUpdate = Upload-MeridianDocumentContent -BaseUrl $BaseUrl -PipelineId $pipelineId -FileName $updateDoc.FileName -Content $updateDoc.Content -SkipCertificateCheck:$SkipCertificateCheck
$updateJobId = Get-Property -Object $uploadUpdate -Names 'JobId','jobId'
if ($updateJobId) {
    Wait-MeridianJob -BaseUrl $BaseUrl -PipelineId $pipelineId -JobId $updateJobId -SkipCertificateCheck:$SkipCertificateCheck | Out-Null
}

Write-Host "Triggering incremental refresh..." -ForegroundColor DarkGray
$refreshResponse = Invoke-MeridianRequest -BaseUrl $BaseUrl -Path "/api/pipelines/$pipelineId/refresh" -Method 'POST' -SkipCertificateCheck:$SkipCertificateCheck
$refreshJobId = Get-Property -Object $refreshResponse -Names 'JobId','jobId'
if ($refreshJobId) {
    Wait-MeridianJob -BaseUrl $BaseUrl -PipelineId $pipelineId -JobId $refreshJobId -SkipCertificateCheck:$SkipCertificateCheck | Out-Null
}

$deliverableAfterRefresh = Get-MeridianDeliverable -BaseUrl $BaseUrl -PipelineId $pipelineId -SkipCertificateCheck:$SkipCertificateCheck
if ($deliverableAfterRefresh) {
    $path = Join-Path $OutputDirectory ("scenario-c-refreshed-" + (Get-Date -Format 'yyyyMMdd-HHmmss') + ".md")
    [System.IO.File]::WriteAllText($path, $deliverableAfterRefresh.Markdown)
    Write-Host "Deliverable after refresh saved to $path" -ForegroundColor Green
} else {
    Write-Warning "No deliverable retrieved after refresh."        
}

Write-Host "Scenario C complete. Pipeline: $pipelineId" -ForegroundColor Cyan
