param(
    [string]$BaseUrl = "http://localhost:5080",
    [switch]$SkipCertificateCheck,
    [string]$OutputDirectory = ""
)

$scriptRoot = Split-Path -Parent $PSCommandPath
. (Join-Path $scriptRoot 'phase4.5-common.ps1')

if ([string]::IsNullOrWhiteSpace($OutputDirectory)) {
    $OutputDirectory = Join-Path $scriptRoot 'output'
}

New-Item -ItemType Directory -Path $OutputDirectory -Force | Out-Null

Write-Host "======================================================================" -ForegroundColor Cyan
Write-Host "Scenario A - Enterprise Architecture Review (WITH AUTHORITATIVE NOTES)" -ForegroundColor Cyan
Write-Host "======================================================================" -ForegroundColor Cyan
Write-Host "Base URL: $BaseUrl" -ForegroundColor DarkGray
Write-Host ""

# Source type definitions - Tags, DescriptorHints, and SignalPhrases generated by AI from prompt
$sourcePrompts = @(
    @{ Prompt = "Meeting notes focusing on enterprise architecture discussions, decisions, and action items." },
    @{ Prompt = "Customer technical bulletin summarizing product updates and integration highlights for clients." },
    @{ Prompt = "Vendor prescreen questionnaire responses describing revenue figures, staffing levels, certifications, and capabilities." },
    @{ Prompt = "Cybersecurity risk assessment summarizing current controls, findings, and remediation guidance." }
)

Write-Host "[1/7] Creating source types via AI..." -ForegroundColor Yellow
$sourceTypes = @()
foreach ($entry in $sourcePrompts) {
    $created = Ensure-MeridianSourceTypeAi -BaseUrl $BaseUrl -Prompt $entry.Prompt -SkipCertificateCheck:$SkipCertificateCheck
    $sourceTypes += $created
    $sourceName = Get-Property -Object $created -Names 'Name','name'
    $sourceId = Get-Property -Object $created -Names 'Id','id'
    Write-Host "  Source type ready: $sourceName ($sourceId)" -ForegroundColor DarkGray
}

$sourceTypeIds = $sourceTypes | ForEach-Object { Get-Property -Object $_ -Names 'Id','id' }

Write-Host "[2/7] Creating analysis type via AI..." -ForegroundColor Yellow
$analysis = Ensure-MeridianAnalysisTypeAi -BaseUrl $BaseUrl -Goal "Produce an enterprise architecture readiness review synthesizing meeting notes, customer bulletins, vendor questionnaires, and cybersecurity assessments." -Audience "CIO steering committee" -IncludedSourceTypes $sourceTypeIds -AdditionalContext "Emphasize key findings, financial health, staffing, and security posture. Use concise markdown sections." -SkipCertificateCheck:$SkipCertificateCheck
$analysisId = Get-Property -Object $analysis -Names 'Id','id'
$analysisName = Get-Property -Object $analysis -Names 'Name','name'
Write-Host "  Analysis type ready: $analysisName ($analysisId)" -ForegroundColor DarkGray

# Pipeline definition - schema and template come from AnalysisType automatically via hook
Write-Host "[3/7] Creating pipeline..." -ForegroundColor Yellow
$pipelineDefinition = [ordered]@{
    Name             = "Enterprise Architecture Review (with Notes) " + (Get-Date -Format 'yyyyMMdd-HHmmss')
    Description      = "Pipeline generated by Scenario A script - testing Authoritative Notes feature"
    AnalysisTypeId   = $analysisId
}

$pipeline = New-MeridianPipeline -BaseUrl $BaseUrl -Definition $pipelineDefinition -SkipCertificateCheck:$SkipCertificateCheck
$pipelineId = Get-Property -Object $pipeline -Names 'Id','id'
Write-Host "  Pipeline created: $pipelineId" -ForegroundColor DarkGray

# ===== NEW: Test Authoritative Notes Feature =====
Write-Host ""
Write-Host "[4/7] Setting Authoritative Notes (Testing Override Feature)..." -ForegroundColor Yellow

# Notes that should override extracted values
$authoritativeNotes = @"
PRIMARY CONTACT: Jordan Kim is actually the VP of Enterprise Solutions (title correction)
REVENUE: FY2024 revenue was exactly `$52.3M USD (updated from preliminary report)
EMPLOYEE COUNT: 175 total employees as of October 2024 (up from 150)
CERTIFICATION: ISO 27001:2022 and SOC 2 Type II both current
PILOT DEADLINE: Integration gateway pilot moved to 2025-11-30 (pushed back 2 weeks)
CIO: Dana Wright (confirmed title: Chief Information Officer)
SECURITY LEAD: Priya Shah - Director of Security Operations
"@

$notesRequest = @{
    authoritativeNotes = $authoritativeNotes
    reProcess = $false  # Don't re-process yet, just set the notes
}

$notesResponse = Invoke-MeridianRequest -BaseUrl $BaseUrl -Path "/api/pipelines/$pipelineId/notes" -Method PUT -Body $notesRequest -SkipCertificateCheck:$SkipCertificateCheck

Write-Host "  Authoritative Notes set successfully" -ForegroundColor Green
Write-Host "  Notes content (preview):" -ForegroundColor DarkGray
($authoritativeNotes -split "`n" | Select-Object -First 3) | ForEach-Object { Write-Host "    $_" -ForegroundColor DarkGray }
Write-Host "    ..." -ForegroundColor DarkGray

# Verify we can retrieve the notes
Write-Host ""
Write-Host "  Verifying Notes retrieval..." -ForegroundColor DarkGray
$retrievedNotes = Invoke-MeridianRequest -BaseUrl $BaseUrl -Path "/api/pipelines/$pipelineId/notes" -Method GET -SkipCertificateCheck:$SkipCertificateCheck
$notesContent = Get-Property -Object $retrievedNotes -Names 'AuthoritativeNotes','authoritativeNotes'

if ($notesContent) {
    Write-Host "  ✓ Notes retrieved successfully ($($notesContent.Length) characters)" -ForegroundColor Green
} else {
    Write-Warning "  Failed to retrieve Authoritative Notes"
}

# ===== END: Authoritative Notes Testing =====

Write-Host ""
Write-Host "[5/7] Uploading documents..." -ForegroundColor Yellow
$documents = @(
    @{ FileName = "meeting-notes.txt"; Content = @"
Arcadia Systems Architecture Steering Committee - 2025-10-20
Attendees: CIO Dana Wright, Lead Architect Leo Martinez, Vendor Liaison Priya Shah.
Agenda focused on the Atlas modernization initiative and partner selection timeline.
Key discussion: Synapse Analytics committed to piloting the integration gateway by 2025-11-15.
Action: Infrastructure team (owner: Morgan Ellis) to prepare sandbox credentials for Synapse by next Monday.
"@.Trim() },
    @{ FileName = "customer-bulletin.txt"; Content = @"
Customer Technical Bulletin - October 2025
Arcadia Systems announces Atlas 4.2 with expanded telemetry sharing and a guided onboarding assistant.
Highlights:
- Early access program opens 2025-11-01 for retail clients.
- Dedicated success engineer Camila Torres assigned to top-tier customers.
- Webinar series scheduled with regional partner NovaBridge to demonstrate integration playbooks.
"@.Trim() },
    @{ FileName = "vendor-prescreen.txt"; Content = @"
Vendor Prescreen Questionnaire - Synapse Analytics
Primary contact: Jordan Kim (Director of Enterprise Accounts).
Financial snapshot: FY2024 revenue reported as 47.2 million USD; staffing count 150 (with 35 engineers assigned to Arcadia engagements).
Differentiators: ISO 27001 certification, 24/7 support desk, regional data residency in NA and EU.
Requested references: Northwind Co., BlueRidge Health.
"@.Trim() },
    @{ FileName = "cybersecurity-assessment.txt"; Content = @"
Cybersecurity Risk Assessment - Synapse Analytics
Conducted by Arcadia Security Office lead Priya Shah on 2025-10-18.
Observations:
- Zero trust network segmentation implemented; SOC 2 Type II in place.
- Minor finding: log retention policy currently 10 months (Arcadia standard requires 12); remediation planned by 2025-12-31.
- No evidence of critical vulnerabilities across portal or API endpoints.
Conclusion: Approved for controlled production rollout with quarterly security reviews.
"@.Trim() }
)

$jobs = @()
foreach ($doc in $documents) {
    Write-Host "  Uploading: $($doc.FileName)..." -ForegroundColor DarkGray
    $upload = Upload-MeridianDocumentContent -BaseUrl $BaseUrl -PipelineId $pipelineId -FileName $doc.FileName -Content $doc.Content -SkipCertificateCheck:$SkipCertificateCheck
    $jobId = Get-Property -Object $upload -Names 'JobId','jobId'
    if ($jobId) {
        Write-Host "    Job scheduled: $jobId" -ForegroundColor DarkGray
        $job = Wait-MeridianJob -BaseUrl $BaseUrl -PipelineId $pipelineId -JobId $jobId -SkipCertificateCheck:$SkipCertificateCheck
        $jobs += $job
        $jobStatus = Get-Property -Object $job -Names 'Status','status'
        Write-Host "    Job completed: $jobStatus" -ForegroundColor DarkGray
    }
}

Write-Host ""
Write-Host "[6/7] Retrieving deliverable..." -ForegroundColor Yellow
Start-Sleep -Seconds 2  # Brief pause to ensure deliverable is ready

$deliverable = Get-MeridianDeliverable -BaseUrl $BaseUrl -PipelineId $pipelineId -SkipCertificateCheck:$SkipCertificateCheck

if ($deliverable) {
    $outputPath = Join-Path $OutputDirectory ("scenario-a-with-notes-" + (Get-Date -Format 'yyyyMMdd-HHmmss') + ".md")
    $markdown = Get-Property -Object $deliverable -Names 'RenderedMarkdown','renderedMarkdown','Markdown','markdown'

    if ($markdown) {
        [System.IO.File]::WriteAllText($outputPath, $markdown)
        Write-Host "  ✓ Deliverable saved to: $outputPath" -ForegroundColor Green

        # Display data JSON to show Notes-sourced fields
        $dataJson = Get-Property -Object $deliverable -Names 'DataJson','dataJson'
        if ($dataJson) {
            Write-Host ""
            Write-Host "  Data payload (preview):" -ForegroundColor DarkGray
            try {
                $data = $dataJson | ConvertFrom-Json
                $fields = Get-Property -Object $data -Names 'fields'
                if ($fields) {
                    Write-Host "    Fields extracted:" -ForegroundColor DarkGray
                    $fields.PSObject.Properties | Select-Object -First 5 | ForEach-Object {
                        $value = $_.Value
                        if ($value -is [string] -and $value.Length -gt 50) {
                            $value = $value.Substring(0, 50) + "..."
                        }
                        Write-Host "      - $($_.Name): $value" -ForegroundColor DarkGray
                    }
                }
            } catch {
                Write-Host "    (Could not parse data JSON)" -ForegroundColor DarkGray
            }
        }
    } else {
        Write-Warning "Deliverable has no markdown content."
    }
} else {
    Write-Warning "No deliverable was generated."
}

Write-Host ""
Write-Host "[7/7] Checking quality metrics for Notes usage..." -ForegroundColor Yellow

# Get pipeline details to check quality metrics
$updatedPipeline = Invoke-MeridianRequest -BaseUrl $BaseUrl -Path "/api/pipelines/$pipelineId" -Method GET -SkipCertificateCheck:$SkipCertificateCheck

$quality = Get-Property -Object $updatedPipeline -Names 'Quality','quality'
if ($quality) {
    $notesSourced = Get-Property -Object $quality -Names 'NotesSourced','notesSourced'
    $highConfidence = Get-Property -Object $quality -Names 'HighConfidence','highConfidence'
    $totalConflicts = Get-Property -Object $quality -Names 'TotalConflicts','totalConflicts'

    Write-Host "  Quality Metrics:" -ForegroundColor DarkGray
    Write-Host "    Fields from Authoritative Notes: $notesSourced" -ForegroundColor $(if ($notesSourced -gt 0) { 'Green' } else { 'Yellow' })
    Write-Host "    High Confidence Fields: $highConfidence" -ForegroundColor DarkGray
    Write-Host "    Total Conflicts: $totalConflicts" -ForegroundColor DarkGray

    if ($notesSourced -gt 0) {
        Write-Host ""
        Write-Host "  ✓ SUCCESS: Authoritative Notes feature working!" -ForegroundColor Green
        Write-Host "    $notesSourced fields were successfully sourced from Notes and overrode document extractions" -ForegroundColor Green
    } else {
        Write-Host ""
        Write-Warning "  No fields were sourced from Authoritative Notes (this may be expected if field names didn't match)"
    }
} else {
    Write-Warning "  Could not retrieve quality metrics"
}

Write-Host ""
Write-Host "======================================================================" -ForegroundColor Cyan
Write-Host "Scenario A Complete!" -ForegroundColor Cyan
Write-Host "======================================================================" -ForegroundColor Cyan
Write-Host "Pipeline ID: $pipelineId" -ForegroundColor White
Write-Host "Authoritative Notes: Set with 7 override fields" -ForegroundColor White
Write-Host "Documents Processed: $($documents.Count)" -ForegroundColor White
if ($deliverable) {
    Write-Host "Deliverable: Generated successfully" -ForegroundColor Green
}
Write-Host ""
Write-Host "Expected Overrides (from Authoritative Notes):" -ForegroundColor Yellow
Write-Host "  - Primary Contact Title: 'VP of Enterprise Solutions' (vs 'Director')" -ForegroundColor DarkGray
Write-Host "  - FY2024 Revenue: '`$52.3M' (vs '`$47.2M' from docs)" -ForegroundColor DarkGray
Write-Host "  - Employee Count: '175' (vs '150' from docs)" -ForegroundColor DarkGray
Write-Host "  - Pilot Deadline: '2025-11-30' (vs '2025-11-15' from docs)" -ForegroundColor DarkGray
Write-Host ""
