param(
    [string]$BaseUrl = "http://localhost:5080",
    [switch]$SkipCertificateCheck,
    [string]$OutputDirectory = ""
)

$scriptRoot = Split-Path -Parent $PSCommandPath
. (Join-Path $scriptRoot 'phase4.5-common.ps1')

if ([string]::IsNullOrWhiteSpace($OutputDirectory)) {
    $OutputDirectory = Join-Path $scriptRoot 'output'
}

New-Item -ItemType Directory -Path $OutputDirectory -Force | Out-Null

Write-Host "Scenario E - Override Escalation & Reversion" -ForegroundColor Cyan
Write-Host "Base URL: $BaseUrl" -ForegroundColor DarkGray

$sourcePrompts = @(
    @{ Prompt = "Meeting notes documenting architecture evaluation steps and next actions."; Tags = @("meeting","architecture"); TargetFields = @("$.notes") },
    @{ Prompt = "Vendor questionnaire responses highlighting revenue, staffing, and certifications."; Tags = @("vendor","finance"); TargetFields = @("$.revenue","$.employees") }
)

$sourceTypes = @()
foreach ($entry in $sourcePrompts) {
    $created = Ensure-MeridianSourceTypeAi -BaseUrl $BaseUrl -Prompt $entry.Prompt -TargetFields $entry.TargetFields -DesiredTags $entry.Tags -SkipCertificateCheck:$SkipCertificateCheck
    $sourceTypes += $created
    $sourceName = Get-Property -Object $created -Names 'Name','name'
    $sourceId = Get-Property -Object $created -Names 'Id','id'
    Write-Host "Source type ready: $sourceName ($sourceId)" -ForegroundColor DarkGray
}

$sourceTypeIds = $sourceTypes | ForEach-Object { Get-Property -Object $_ -Names 'Id','id' }

$analysis = Ensure-MeridianAnalysisTypeAi -BaseUrl $BaseUrl -Goal "Summarize vendor posture with emphasis on revenue accuracy and staffing levels." -Audience "Architecture finance reviewers" -IncludedSourceTypes $sourceTypeIds -AdditionalContext "Highlight when overrides are applied and ensure markdown includes a staffing bullet." -SkipCertificateCheck:$SkipCertificateCheck
$analysisId = Get-Property -Object $analysis -Names 'Id','id'
$analysisTemplate = Get-Property -Object $analysis -Names 'OutputTemplate','outputTemplate','TemplateMarkdown','templateMarkdown'
Write-Host "Analysis type ready: $(Get-Property -Object $analysis -Names 'Name','name') ($analysisId)" -ForegroundColor DarkGray

$schemaJson = @"
{
  "type": "object",
  "properties": {
    "revenue": { "type": "number" },
    "employees": { "type": "number" }
  }
}
"@

$pipelineDefinition = [ordered]@{
    Name             = "Override Reversion Pipeline " + (Get-Date -Format 'yyyyMMdd-HHmmss')
    Description      = "Pipeline generated by Scenario E"
    AnalysisTypeId   = $analysisId
    SchemaJson       = $schemaJson
    TemplateMarkdown = if ($analysisTemplate) { $analysisTemplate } else { "# Vendor Summary`nRevenue: {{revenue}}`nEmployees: {{employees}}" }
}

$pipeline = New-MeridianPipeline -BaseUrl $BaseUrl -Definition $pipelineDefinition -SkipCertificateCheck:$SkipCertificateCheck
$pipelineId = Get-Property -Object $pipeline -Names 'Id','id'
Write-Host "Pipeline created: $pipelineId" -ForegroundColor DarkGray

$baselineDocs = @(
    @{ FileName = "meeting-baseline.txt"; Content = "Architecture steering meeting notes focusing on vendor review." },
    @{ FileName = "vendor-baseline.txt"; Content = "Vendor questionnaire baseline: revenue 47.2 million USD; employees 150." }
)

foreach ($doc in $baselineDocs) {
    $upload = Upload-MeridianDocumentContent -BaseUrl $BaseUrl -PipelineId $pipelineId -FileName $doc.FileName -Content $doc.Content -SkipCertificateCheck:$SkipCertificateCheck
    $jobId = Get-Property -Object $upload -Names 'JobId','jobId'
    if ($jobId) {
        Wait-MeridianJob -BaseUrl $BaseUrl -PipelineId $pipelineId -JobId $jobId -SkipCertificateCheck:$SkipCertificateCheck | Out-Null
    }
}

$employeeField = [System.Uri]::EscapeDataString('$.employees')
$overrideRequest = @{ value = 162; reason = "Staffing override supplied by HR"; reviewer = "scenario-e" }
Invoke-MeridianRequest -BaseUrl $BaseUrl -Path "/api/pipelines/$pipelineId/fields/$employeeField/override" -Method 'POST' -Body $overrideRequest -SkipCertificateCheck:$SkipCertificateCheck | Out-Null

$deliverableOverride = Get-MeridianDeliverable -BaseUrl $BaseUrl -PipelineId $pipelineId -SkipCertificateCheck:$SkipCertificateCheck
if ($deliverableOverride) {
    $overridePath = Join-Path $OutputDirectory ("scenario-e-override-" + (Get-Date -Format 'yyyyMMdd-HHmmss') + ".md")
    [System.IO.File]::WriteAllText($overridePath, $deliverableOverride.Markdown)
    Write-Host "Override deliverable saved to $overridePath" -ForegroundColor Green
}

Invoke-MeridianRequest -BaseUrl $BaseUrl -Path "/api/pipelines/$pipelineId/fields/$employeeField/override" -Method 'DELETE' -SkipCertificateCheck:$SkipCertificateCheck | Out-Null

Write-Host "Triggering refresh to reinstate AI value..." -ForegroundColor DarkGray
$refreshResponse = Invoke-MeridianRequest -BaseUrl $BaseUrl -Path "/api/pipelines/$pipelineId/refresh" -Method 'POST' -SkipCertificateCheck:$SkipCertificateCheck
$refreshJobId = Get-Property -Object $refreshResponse -Names 'JobId','jobId'
if ($refreshJobId) {
    Wait-MeridianJob -BaseUrl $BaseUrl -PipelineId $pipelineId -JobId $refreshJobId -SkipCertificateCheck:$SkipCertificateCheck | Out-Null
}

$deliverableCleared = Get-MeridianDeliverable -BaseUrl $BaseUrl -PipelineId $pipelineId -SkipCertificateCheck:$SkipCertificateCheck
if ($deliverableCleared) {
    $clearedPath = Join-Path $OutputDirectory ("scenario-e-reverted-" + (Get-Date -Format 'yyyyMMdd-HHmmss') + ".md")
    [System.IO.File]::WriteAllText($clearedPath, $deliverableCleared.Markdown)
    Write-Host "Deliverable after reverting override saved to $clearedPath" -ForegroundColor Green
    if ($deliverableCleared.Markdown -match "162") {
        Write-Warning "Override value still present; investigate."        
    }
} else {
    Write-Warning "Deliverable not available after reversion."        
}

Write-Host "Scenario E complete. Override removed and AI value reinstated." -ForegroundColor Cyan
