param(
    [string]$BaseUrl = "http://localhost:5080",
    [switch]$SkipCertificateCheck,
    [string]$OutputDirectory = ""
)

$scriptRoot = Split-Path -Parent $PSCommandPath
. (Join-Path $scriptRoot 'phase4.5-common.ps1')

if ([string]::IsNullOrWhiteSpace($OutputDirectory)) {
    $OutputDirectory = Join-Path $scriptRoot 'output'
}

New-Item -ItemType Directory -Path $OutputDirectory -Force | Out-Null

Write-Host "Scenario A - Enterprise Architecture Review" -ForegroundColor Cyan
Write-Host "Base URL: $BaseUrl" -ForegroundColor DarkGray

# Source type definitions - Tags, DescriptorHints, and SignalPhrases generated by AI from prompt
$sourcePrompts = @(
    @{ Prompt = "Meeting notes focusing on enterprise architecture discussions, decisions, and action items." },
    @{ Prompt = "Customer technical bulletin summarizing product updates and integration highlights for clients." },
    @{ Prompt = "Vendor prescreen questionnaire responses describing revenue figures, staffing levels, certifications, and capabilities." },
    @{ Prompt = "Cybersecurity risk assessment summarizing current controls, findings, and remediation guidance." }
)

$sourceTypes = @()
foreach ($entry in $sourcePrompts) {
    $created = Ensure-MeridianSourceTypeAi -BaseUrl $BaseUrl -Prompt $entry.Prompt -SkipCertificateCheck:$SkipCertificateCheck
    $sourceTypes += $created
    $sourceName = Get-Property -Object $created -Names 'Name','name'
    $sourceId = Get-Property -Object $created -Names 'Id','id'
    Write-Host "Source type ready: $sourceName ($sourceId)" -ForegroundColor DarkGray
}

$sourceTypeIds = $sourceTypes | ForEach-Object { Get-Property -Object $_ -Names 'Id','id' }

$timestamp = Get-Date -Format 'yyyyMMdd-HHmmss'

$baselineSchema = [ordered]@{
    '$schema'   = 'http://json-schema.org/draft-07/schema#'
    type        = 'object'
    properties  = [ordered]@{
        executive_summary   = @{ type = 'string'; description = 'Summary of modernization goals, key decisions, and stakeholder commitments.' }
        integration_timeline = @{ type = 'string'; description = 'Critical integration milestones, owners, and due dates.' }
        vendor_snapshot     = @{ type = 'string'; description = 'Financial posture, staffing coverage, and differentiators for primary vendors.' }
    }
    required    = @('executive_summary', 'integration_timeline', 'vendor_snapshot')
}

$baselineSchemaJson = ($baselineSchema | ConvertTo-Json -Depth 10)

$baselineInstructions = @"
Populate the enterprise architecture readiness brief with crisp paragraphs for each JSON field:
- executive_summary: modernization goals, key decisions, and partner commitments.
- integration_timeline: milestone dates, responsible owners, and immediate next steps.
- vendor_snapshot: financial posture, staffing coverage, certifications, and standout differentiators.
Use only evidence found in the uploaded documents.
"@.Trim()

$baselineTemplate = @"
# Enterprise Architecture Readiness
## Executive Summary
{{executive_summary}}

## Integration Timeline
{{integration_timeline}}

## Vendor Snapshot
{{vendor_snapshot}}
"@.Trim()

$analysisName = "Scenario A Enterprise Architecture Baseline $timestamp"
$analysisDefinition = [ordered]@{
    Name           = $analysisName
    Description    = "Scenario A baseline enterprise architecture readiness assessment generated by automation script."
    Instructions   = $baselineInstructions
    OutputTemplate = $baselineTemplate
    JsonSchema     = $baselineSchemaJson
    Tags           = @('scenario-a','enterprise','architecture')
    Descriptors    = @('baseline','readiness')
    Version        = 1
}

$analysis = Invoke-MeridianRequest -BaseUrl $BaseUrl -Path '/api/analysistypes' -Method 'POST' -Body $analysisDefinition -SkipCertificateCheck:$SkipCertificateCheck
$analysisId = Get-Property -Object $analysis -Names 'Id','id'
Write-Host "Analysis type ready: $analysisName ($analysisId)" -ForegroundColor DarkGray

# Pipeline definition - schema and template come from AnalysisType automatically via hook
$pipelineDefinition = [ordered]@{
    Name             = "Enterprise Architecture Review " + (Get-Date -Format 'yyyyMMdd-HHmmss')
    Description      = "Pipeline generated by Scenario A script"
    AnalysisTypeId   = $analysisId
    SchemaJson       = $baselineSchemaJson
    TemplateMarkdown = $baselineTemplate
    AnalysisInstructions = $baselineInstructions
}

$pipeline = New-MeridianPipeline -BaseUrl $BaseUrl -Definition $pipelineDefinition -SkipCertificateCheck:$SkipCertificateCheck
$pipelineId = Get-Property -Object $pipeline -Names 'Id','id'
Write-Host "Pipeline created: $pipelineId" -ForegroundColor DarkGray

$documents = @(
    @{ FileName = "meeting-notes.txt"; Content = @"
Arcadia Systems Architecture Steering Committee - 2025-10-20
Attendees: CIO Dana Wright, Lead Architect Leo Martinez, Vendor Liaison Priya Shah.
Agenda focused on the Atlas modernization initiative and partner selection timeline.
Key discussion: Synapse Analytics committed to piloting the integration gateway by 2025-11-15.
Action: Infrastructure team (owner: Morgan Ellis) to prepare sandbox credentials for Synapse by next Monday.
"@.Trim() },
    @{ FileName = "customer-bulletin.txt"; Content = @"
Customer Technical Bulletin - October 2025
Arcadia Systems announces Atlas 4.2 with expanded telemetry sharing and a guided onboarding assistant.
Highlights:
- Early access program opens 2025-11-01 for retail clients.
- Dedicated success engineer Camila Torres assigned to top-tier customers.
- Webinar series scheduled with regional partner NovaBridge to demonstrate integration playbooks.
"@.Trim() },
    @{ FileName = "vendor-prescreen.txt"; Content = @"
Vendor Prescreen Questionnaire - Synapse Analytics
Primary contact: Jordan Kim (Director of Enterprise Accounts).
Financial snapshot: FY2024 revenue reported as 47.2 million USD; staffing count 150 (with 35 engineers assigned to Arcadia engagements).
Differentiators: ISO 27001 certification, 24/7 support desk, regional data residency in NA and EU.
Requested references: Northwind Co., BlueRidge Health.
"@.Trim() },
    @{ FileName = "cybersecurity-assessment.txt"; Content = @"
Cybersecurity Risk Assessment - Synapse Analytics
Conducted by Arcadia Security Office lead Priya Shah on 2025-10-18.
Observations:
- Zero trust network segmentation implemented; SOC 2 Type II in place.
- Minor finding: log retention policy currently 10 months (Arcadia standard requires 12); remediation planned by 2025-12-31.
- No evidence of critical vulnerabilities across portal or API endpoints.
Conclusion: Approved for controlled production rollout with quarterly security reviews.
"@.Trim() }
)

$jobs = @()
foreach ($doc in $documents) {
    $upload = Upload-MeridianDocumentContent -BaseUrl $BaseUrl -PipelineId $pipelineId -FileName $doc.FileName -Content $doc.Content -SkipCertificateCheck:$SkipCertificateCheck
    $jobId = Get-Property -Object $upload -Names 'JobId','jobId'
    if ($jobId) {
        $job = Wait-MeridianJob -BaseUrl $BaseUrl -PipelineId $pipelineId -JobId $jobId -SkipCertificateCheck:$SkipCertificateCheck
        $jobs += $job
    }
}

$deliverable = Get-MeridianDeliverable -BaseUrl $BaseUrl -PipelineId $pipelineId -SkipCertificateCheck:$SkipCertificateCheck
if ($deliverable) {
    $outputPath = Join-Path $OutputDirectory ("scenario-a-deliverable-" + (Get-Date -Format 'yyyyMMdd-HHmmss') + ".md")
    $markdown = Get-Property -Object $deliverable -Names 'RenderedMarkdown','renderedMarkdown','Markdown','markdown'
    if ($markdown) {
        [System.IO.File]::WriteAllText($outputPath, $markdown)
        Write-Host "Deliverable saved to $outputPath" -ForegroundColor Green
    } else {
        Write-Warning "Deliverable has no markdown content."
    }
} else {
    Write-Warning "No deliverable was generated."
}

Write-Host "Extending analysis to capture staffing and security coverage..." -ForegroundColor DarkGray

$extendedSchema = [ordered]@{
    '$schema'   = $baselineSchema.'$schema'
    type        = 'object'
    properties  = [ordered]@{
        executive_summary    = $baselineSchema.properties['executive_summary']
        integration_timeline = $baselineSchema.properties['integration_timeline']
        vendor_snapshot      = $baselineSchema.properties['vendor_snapshot']
        staffing_profile     = @{ type = 'string'; description = 'Staffing allocation, lead coverage, and capacity signals supporting the modernization program.' }
        security_highlights  = @{ type = 'string'; description = 'Salient cybersecurity controls, audit findings, and remediation commitments.' }
    }
    required    = @('executive_summary','integration_timeline','vendor_snapshot','staffing_profile','security_highlights')
}

$extendedSchemaJson = ($extendedSchema | ConvertTo-Json -Depth 10)

$extendedInstructions = @"
Extend the readiness brief by adding two new sections:
- staffing_profile: summarize headcount allocation, named leads, and coverage risks that support the modernization initiative.
- security_highlights: capture key cybersecurity controls, audit observations, and planned remediation timelines.
Continue to refresh the existing fields (executive_summary, integration_timeline, vendor_snapshot) using the current document set.
"@.Trim()

$extendedTemplate = @"
# Enterprise Architecture Readiness (Extended)
## Executive Summary
{{executive_summary}}

## Integration Timeline
{{integration_timeline}}

## Vendor Snapshot
{{vendor_snapshot}}

## Staffing Profile
{{staffing_profile}}

## Security Highlights
{{security_highlights}}
"@.Trim()

$currentVersion = Get-Property -Object $analysis -Names 'Version','version'
if (-not $currentVersion) { $currentVersion = 1 }

$analysisPatch = [ordered]@{
    Instructions      = $extendedInstructions
    OutputTemplate    = $extendedTemplate
    JsonSchema        = $extendedSchemaJson
    Description       = "Scenario A extended enterprise architecture assessment including staffing and security coverage."
    Version           = [int]$currentVersion + 1
}

Invoke-MeridianRequest -BaseUrl $BaseUrl -Path "/api/analysistypes/$analysisId" -Method 'PATCH' -Body $analysisPatch -SkipCertificateCheck:$SkipCertificateCheck | Out-Null
$analysis = Invoke-MeridianRequest -BaseUrl $BaseUrl -Path "/api/analysistypes/$analysisId" -SkipCertificateCheck:$SkipCertificateCheck

$pipelinePatch = [ordered]@{
    TemplateMarkdown     = $extendedTemplate
    SchemaJson           = $extendedSchemaJson
    AnalysisInstructions = $extendedInstructions
    UpdatedAt            = [DateTime]::UtcNow
}

Invoke-MeridianRequest -BaseUrl $BaseUrl -Path "/api/pipelines/$pipelineId" -Method 'PATCH' -Body $pipelinePatch -SkipCertificateCheck:$SkipCertificateCheck | Out-Null

$refreshResponse = Invoke-MeridianRequest -BaseUrl $BaseUrl -Path "/api/pipelines/$pipelineId/refresh" -Method 'POST' -SkipCertificateCheck:$SkipCertificateCheck
$refreshJobId = Get-Property -Object $refreshResponse -Names 'JobId','jobId'
if ($refreshJobId) {
    Wait-MeridianJob -BaseUrl $BaseUrl -PipelineId $pipelineId -JobId $refreshJobId -SkipCertificateCheck:$SkipCertificateCheck | Out-Null
}

$extendedDeliverable = Get-MeridianDeliverable -BaseUrl $BaseUrl -PipelineId $pipelineId -SkipCertificateCheck:$SkipCertificateCheck
if ($extendedDeliverable) {
    $extendedPath = Join-Path $OutputDirectory ("scenario-a-extended-deliverable-" + (Get-Date -Format 'yyyyMMdd-HHmmss') + ".md")
    $extendedMarkdown = Get-Property -Object $extendedDeliverable -Names 'RenderedMarkdown','renderedMarkdown','Markdown','markdown'
    if ($extendedMarkdown) {
        [System.IO.File]::WriteAllText($extendedPath, $extendedMarkdown)
        Write-Host "Extended deliverable saved to $extendedPath" -ForegroundColor Green
    } else {
        Write-Warning "Extended deliverable has no markdown content."
    }
} else {
    Write-Warning "No extended deliverable was generated after refresh."
}

Write-Host "Scenario A complete. Pipeline: $pipelineId" -ForegroundColor Cyan
