param(
    [string]$BaseUrl = "http://localhost:5080",
    [switch]$SkipCertificateCheck,
    [string]$OutputDirectory = ""
)

# Load required .NET assemblies for HTTP operations
Add-Type -AssemblyName System.Net.Http

$scriptRoot = Split-Path -Parent $PSCommandPath
. (Join-Path $scriptRoot 'phase4.5-common.ps1')

if ([string]::IsNullOrWhiteSpace($OutputDirectory)) {
    $OutputDirectory = Join-Path $scriptRoot 'output'
}

New-Item -ItemType Directory -Path $OutputDirectory -Force | Out-Null

Write-Host "Scenario A - Enterprise Architecture Review (File-Only API)" -ForegroundColor Cyan
Write-Host "Base URL: $BaseUrl" -ForegroundColor DarkGray

# Step 1: Discover available type codes
Write-Host "Discovering available type codes..." -ForegroundColor Yellow
$analysisTypes = Invoke-MeridianRequest -BaseUrl $BaseUrl -Path '/api/analysistypes/codes' -Method 'GET' -SkipCertificateCheck:$SkipCertificateCheck
$sourceTypes = Invoke-MeridianRequest -BaseUrl $BaseUrl -Path '/api/sourcetypes/codes' -Method 'GET' -SkipCertificateCheck:$SkipCertificateCheck

$analysisTypesList = Get-Property -Object $analysisTypes -Names 'types','Types'
$sourceTypesList = Get-Property -Object $sourceTypes -Names 'types','Types'

Write-Host "Available analysis types:" -ForegroundColor DarkGray
foreach ($type in $analysisTypesList) {
    $code = Get-Property -Object $type -Names 'code','Code'
    $name = Get-Property -Object $type -Names 'name','Name'
    Write-Host "  - $code : $name" -ForegroundColor DarkGray
}

Write-Host "Available source types:" -ForegroundColor DarkGray
foreach ($type in $sourceTypesList) {
    $code = Get-Property -Object $type -Names 'code','Code'
    $name = Get-Property -Object $type -Names 'name','Name'
    Write-Host "  - $code : $name" -ForegroundColor DarkGray
}

# Step 2: Create configuration file
$timestamp = Get-Date -Format 'yyyyMMdd-HHmmss'
$configData = @{
    pipeline = @{
        name = "Enterprise Architecture Review $timestamp"
        description = "Pipeline generated by Scenario A file-only script"
        notes = @"
Primary vendor: Synapse Analytics
Contact: Jordan Kim (Director of Enterprise Accounts)
FY2024 revenue: 47.2 million USD
Staffing: 150 total, 35 engineers assigned to Arcadia engagements
Key milestone: Integration gateway pilot by 2025-11-15
"@.Trim()
        bias = "Focus on integration timeline and financial stability indicators"
    }
    analysis = @{
        type = "EAR"  # Enterprise Architecture Review
    }
    manifest = @{
        "meeting-notes.txt" = @{
            type = "MEET"
            notes = "Steering committee meeting discussing Atlas modernization"
        }
        "vendor-prescreen.txt" = @{
            type = "CONT"
            notes = "Vendor questionnaire responses from Synapse Analytics"
        }
    }
}

$configJson = $configData | ConvertTo-Json -Depth 10

# Step 3: Create temporary directory for files
$tempDir = Join-Path $env:TEMP ("meridian-scenario-a-" + [guid]::NewGuid().ToString())
New-Item -ItemType Directory -Path $tempDir -Force | Out-Null

try {
    # Write config file
    $configPath = Join-Path $tempDir "analysis-config.json"
    [IO.File]::WriteAllText($configPath, $configJson)
    Write-Host "Created config file: analysis-config.json" -ForegroundColor DarkGray

    # Write document files
    $documents = @(
        @{ FileName = "meeting-notes.txt"; Content = @"
Arcadia Systems Architecture Steering Committee - 2025-10-20
Attendees: CIO Dana Wright, Lead Architect Leo Martinez, Vendor Liaison Priya Shah.
Agenda focused on the Atlas modernization initiative and partner selection timeline.
Key discussion: Synapse Analytics committed to piloting the integration gateway by 2025-11-15.
Action: Infrastructure team (owner: Morgan Ellis) to prepare sandbox credentials for Synapse by next Monday.
"@.Trim() },
        @{ FileName = "customer-bulletin.txt"; Content = @"
Customer Technical Bulletin - October 2025
Arcadia Systems announces Atlas 4.2 with expanded telemetry sharing and a guided onboarding assistant.
Highlights:
- Early access program opens 2025-11-01 for retail clients.
- Dedicated success engineer Camila Torres assigned to top-tier customers.
- Webinar series scheduled with regional partner NovaBridge to demonstrate integration playbooks.
"@.Trim() },
        @{ FileName = "vendor-prescreen.txt"; Content = @"
Vendor Prescreen Questionnaire - Synapse Analytics
Primary contact: Jordan Kim (Director of Enterprise Accounts).
Financial snapshot: FY2024 revenue reported as 47.2 million USD; staffing count 150 (with 35 engineers assigned to Arcadia engagements).
Differentiators: ISO 27001 certification, 24/7 support desk, regional data residency in NA and EU.
Requested references: Northwind Co., BlueRidge Health.
"@.Trim() },
        @{ FileName = "cybersecurity-assessment.txt"; Content = @"
Cybersecurity Risk Assessment - Synapse Analytics
Conducted by Arcadia Security Office lead Priya Shah on 2025-10-18.
Observations:
- Zero trust network segmentation implemented; SOC 2 Type II in place.
- Minor finding: log retention policy currently 10 months (Arcadia standard requires 12); remediation planned by 2025-12-31.
- No evidence of critical vulnerabilities across portal or API endpoints.
Conclusion: Approved for controlled production rollout with quarterly security reviews.
"@.Trim() }
    )

    foreach ($doc in $documents) {
        $docPath = Join-Path $tempDir $doc.FileName
        [IO.File]::WriteAllText($docPath, $doc.Content)
        Write-Host "Created document: $($doc.FileName)" -ForegroundColor DarkGray
    }

    # Step 4: Upload all files via multipart form-data
    Write-Host "Uploading files to /api/pipelines/create..." -ForegroundColor Yellow

    $form = New-Object System.Net.Http.MultipartFormDataContent

    # Add all files to the form
    $allFiles = @($configPath) + ($documents | ForEach-Object { Join-Path $tempDir $_.FileName })

    foreach ($filePath in $allFiles) {
        $fileContent = [System.IO.File]::ReadAllBytes($filePath)
        $fileName = [System.IO.Path]::GetFileName($filePath)
        $fileStream = New-Object System.IO.MemoryStream @(,$fileContent)
        $streamContent = New-Object System.Net.Http.StreamContent($fileStream)
        $streamContent.Headers.ContentType = New-Object System.Net.Http.Headers.MediaTypeHeaderValue("text/plain")
        $form.Add($streamContent, "files", $fileName)
    }

    # Create HttpClient
    $handler = New-Object System.Net.Http.HttpClientHandler
    if ($SkipCertificateCheck) {
        $handler.ServerCertificateCustomValidationCallback = { $true }
    }
    $client = New-Object System.Net.Http.HttpClient($handler)
    $client.Timeout = [TimeSpan]::FromSeconds(300)

    # POST request
    $uri = "$BaseUrl/api/pipelines/create"
    Write-Host "Posting to: $uri" -ForegroundColor DarkGray

    $response = $client.PostAsync($uri, $form).Result
    $responseContent = $response.Content.ReadAsStringAsync().Result

    if (-not $response.IsSuccessStatusCode) {
        Write-Host "Error creating pipeline: $($response.StatusCode)" -ForegroundColor Red
        Write-Host $responseContent -ForegroundColor Red
        exit 1
    }

    $result = $responseContent | ConvertFrom-Json
    Write-Host "Pipeline creation response received" -ForegroundColor Green

    # Display results
    $pipelineId = Get-Property -Object $result -Names 'pipelineId','PipelineId'
    $pipelineName = Get-Property -Object $result -Names 'pipelineName','PipelineName'
    $jobId = Get-Property -Object $result -Names 'jobId','JobId'
    $isCustom = Get-Property -Object $result -Names 'isCustomAnalysis','IsCustomAnalysis'
    $analysisType = Get-Property -Object $result -Names 'analysisType','AnalysisType'
    $analysisTypeName = Get-Property -Object $result -Names 'analysisTypeName','AnalysisTypeName'

    Write-Host ""
    Write-Host "Pipeline created successfully!" -ForegroundColor Green
    Write-Host "  Pipeline ID: $pipelineId" -ForegroundColor Cyan
    Write-Host "  Pipeline Name: $pipelineName" -ForegroundColor Cyan
    Write-Host "  Analysis Type: $analysisTypeName ($analysisType)" -ForegroundColor Cyan
    Write-Host "  Job ID: $jobId" -ForegroundColor Cyan
    Write-Host ""

    # Display document classification results
    $docs = Get-Property -Object $result -Names 'documents','Documents'
    if ($docs) {
        Write-Host "Document Classification Results:" -ForegroundColor Yellow
        foreach ($doc in $docs) {
            $docId = Get-Property -Object $doc -Names 'documentId','DocumentId'
            $fileName = Get-Property -Object $doc -Names 'fileName','FileName'
            $sourceType = Get-Property -Object $doc -Names 'sourceType','SourceType'
            $method = Get-Property -Object $doc -Names 'method','Method'
            $confidence = Get-Property -Object $doc -Names 'confidence','Confidence'
            $inManifest = Get-Property -Object $doc -Names 'inManifest','InManifest'

            $manifestIndicator = if ($inManifest) { "[MANIFEST]" } else { "[AUTO]" }
            Write-Host "  $manifestIndicator $fileName" -ForegroundColor Cyan
            Write-Host "    Source Type: $sourceType" -ForegroundColor DarkGray
            Write-Host "    Method: $method, Confidence: $([Math]::Round($confidence * 100, 1))%" -ForegroundColor DarkGray
        }
        Write-Host ""
    }

    # Display statistics
    $stats = Get-Property -Object $result -Names 'statistics','Statistics'
    if ($stats) {
        $total = Get-Property -Object $stats -Names 'totalDocuments','TotalDocuments'
        $manifest = Get-Property -Object $stats -Names 'manifestSpecified','ManifestSpecified'
        $auto = Get-Property -Object $stats -Names 'autoClassified','AutoClassified'
        Write-Host "Statistics:" -ForegroundColor Yellow
        Write-Host "  Total Documents: $total" -ForegroundColor Cyan
        Write-Host "  Manifest-Specified: $manifest" -ForegroundColor Cyan
        Write-Host "  Auto-Classified: $auto" -ForegroundColor Cyan
        Write-Host ""
    }

    # Step 5: Wait for job completion
    Write-Host "Waiting for job $jobId to complete..." -ForegroundColor Yellow
    $job = Wait-MeridianJob -BaseUrl $BaseUrl -PipelineId $pipelineId -JobId $jobId -SkipCertificateCheck:$SkipCertificateCheck
    Write-Host "Job completed" -ForegroundColor Green

    # Step 6: Get deliverable
    Write-Host "Retrieving deliverable..." -ForegroundColor Yellow
    $deliverable = Get-MeridianDeliverable -BaseUrl $BaseUrl -PipelineId $pipelineId -SkipCertificateCheck:$SkipCertificateCheck

    if ($deliverable) {
        $outputPath = Join-Path $OutputDirectory ("scenario-a-fileonly-deliverable-" + (Get-Date -Format 'yyyyMMdd-HHmmss') + ".md")
        $markdown = Get-Property -Object $deliverable -Names 'RenderedMarkdown','renderedMarkdown','Markdown','markdown'
        if ($markdown) {
            [IO.File]::WriteAllText($outputPath, $markdown)
            Write-Host "Deliverable saved to: $outputPath" -ForegroundColor Green
            Write-Host ""
            Write-Host "Deliverable Content:" -ForegroundColor Yellow
            Write-Host $markdown -ForegroundColor White
        }
    }

} finally {
    # Cleanup
    if (Test-Path $tempDir) {
        Remove-Item -Path $tempDir -Recurse -Force
        Write-Host "Cleaned up temporary files" -ForegroundColor DarkGray
    }
    if ($client) { $client.Dispose() }
    if ($handler) { $handler.Dispose() }
}

Write-Host ""
Write-Host "Scenario A (File-Only) completed successfully!" -ForegroundColor Green
