param(
    [string]$BaseUrl = "http://localhost:5080",
    [switch]$SkipCertificateCheck,
    [string]$OutputDirectory = ""
)

$scriptRoot = Split-Path -Parent $PSCommandPath
. (Join-Path $scriptRoot 'phase4.5-common.ps1')

if ([string]::IsNullOrWhiteSpace($OutputDirectory)) {
    $OutputDirectory = Join-Path $scriptRoot 'output'
}

New-Item -ItemType Directory -Path $OutputDirectory -Force | Out-Null

Write-Host "Scenario B - Single-Field Manual Override" -ForegroundColor Cyan
Write-Host "Base URL: $BaseUrl" -ForegroundColor DarkGray

$sourcePrompts = @(
    @{ Prompt = "Meeting notes covering vendor evaluation discussions for enterprise architecture."; Tags = @("meeting","architecture"); TargetFields = @("$.notes") },
    @{ Prompt = "Vendor questionnaire capturing revenue figures, employee counts, and service capabilities."; Tags = @("vendor","finance"); TargetFields = @("$.revenue","$.employees") }
)

$sourceTypes = @()
foreach ($entry in $sourcePrompts) {
    $created = Ensure-MeridianSourceTypeAi -BaseUrl $BaseUrl -Prompt $entry.Prompt -TargetFields $entry.TargetFields -DesiredTags $entry.Tags -SkipCertificateCheck:$SkipCertificateCheck
    $sourceTypes += $created
    $sourceName = Get-Property -Object $created -Names 'Name','name'
    $sourceId = Get-Property -Object $created -Names 'Id','id'
    Write-Host "Source type ready: $sourceName ($sourceId)" -ForegroundColor DarkGray
}

$sourceTypeIds = $sourceTypes | ForEach-Object { Get-Property -Object $_ -Names 'Id','id' }

$analysis = Ensure-MeridianAnalysisTypeAi -BaseUrl $BaseUrl -Goal "Summarize vendor evaluation notes highlighting revenue and staffing." -Audience "Architecture review board" -IncludedSourceTypes $sourceTypeIds -AdditionalContext "Include concise markdown with key financial metrics and staffing numbers." -SkipCertificateCheck:$SkipCertificateCheck
$analysisId = Get-Property -Object $analysis -Names 'Id','id'
$analysisTemplate = Get-Property -Object $analysis -Names 'OutputTemplate','outputTemplate','TemplateMarkdown','templateMarkdown'
Write-Host "Analysis type ready: $(Get-Property -Object $analysis -Names 'Name','name') ($analysisId)" -ForegroundColor DarkGray

$schemaJson = @"
{
  "type": "object",
  "properties": {
    "revenue": { "type": "number" },
    "employees": { "type": "number" }
  }
}
"@

$pipelineDefinition = [ordered]@{
    Name             = "Manual Override Pipeline " + (Get-Date -Format 'yyyyMMdd-HHmmss')
    Description      = "Pipeline generated by Scenario B"
    AnalysisTypeId   = $analysisId
    SchemaJson       = $schemaJson
    TemplateMarkdown = if ($analysisTemplate) { $analysisTemplate } else { "# Vendor Summary`nRevenue: {{revenue}}`nEmployees: {{employees}}" }
}

$pipeline = New-MeridianPipeline -BaseUrl $BaseUrl -Definition $pipelineDefinition -SkipCertificateCheck:$SkipCertificateCheck
$pipelineId = Get-Property -Object $pipeline -Names 'Id','id'
Write-Host "Pipeline created: $pipelineId" -ForegroundColor DarkGray

$documents = @(
    @{ FileName = "meeting-notes.txt"; Content = "Architecture review meeting: vendor evaluation discussed, highlighting integration requirements." },
    @{ FileName = "vendor-questionnaire.txt"; Content = "Vendor prescreen questionnaire reports annual revenue of 47.2 million USD with 150 employees." }
)

foreach ($doc in $documents) {
    $upload = Upload-MeridianDocumentContent -BaseUrl $BaseUrl -PipelineId $pipelineId -FileName $doc.FileName -Content $doc.Content -SkipCertificateCheck:$SkipCertificateCheck
    $jobId = Get-Property -Object $upload -Names 'JobId','jobId'
    if ($jobId) {
        Wait-MeridianJob -BaseUrl $BaseUrl -PipelineId $pipelineId -JobId $jobId -SkipCertificateCheck:$SkipCertificateCheck | Out-Null
    }
}

$encodedField = [System.Uri]::EscapeDataString('$.revenue')
$overrideRequest = @{ value = 52.5; reason = "Manual correction from finance"; reviewer = "scenario-b" }
Invoke-MeridianRequest -BaseUrl $BaseUrl -Path "/api/pipelines/$pipelineId/fields/$encodedField/override" -Method 'POST' -Body $overrideRequest -SkipCertificateCheck:$SkipCertificateCheck | Out-Null

$deliverableOverride = Get-MeridianDeliverable -BaseUrl $BaseUrl -PipelineId $pipelineId -SkipCertificateCheck:$SkipCertificateCheck
if ($deliverableOverride) {
    $path = Join-Path $OutputDirectory ("scenario-b-override-" + (Get-Date -Format 'yyyyMMdd-HHmmss') + ".md")
    [System.IO.File]::WriteAllText($path, $deliverableOverride.Markdown)
    Write-Host "Deliverable with override saved to $path" -ForegroundColor Green
} else {
    Write-Warning "No deliverable after override."        
}

Invoke-MeridianRequest -BaseUrl $BaseUrl -Path "/api/pipelines/$pipelineId/fields/$encodedField/override" -Method 'DELETE' -SkipCertificateCheck:$SkipCertificateCheck | Out-Null

$deliverableCleared = Get-MeridianDeliverable -BaseUrl $BaseUrl -PipelineId $pipelineId -SkipCertificateCheck:$SkipCertificateCheck
if ($deliverableCleared) {
    $path = Join-Path $OutputDirectory ("scenario-b-cleared-" + (Get-Date -Format 'yyyyMMdd-HHmmss') + ".md")
    [System.IO.File]::WriteAllText($path, $deliverableCleared.Markdown)
    Write-Host "Deliverable after clearing override saved to $path" -ForegroundColor Green
}

Write-Host "Scenario B complete. Pipeline: $pipelineId" -ForegroundColor Cyan
