using System.Net;
using AwesomeAssertions;
using Koan.Data.Abstractions.Annotations;
using Koan.Data.Core.Model;
using Koan.Mcp;
using Koan.Web.Controllers;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Xunit;

namespace Koan.Web.OpenApi.Tests;

/// <summary>
/// AN2 (docs/assessment/09 §8, O1ˢ) — the "one schema projector" question, empirically resolved.
///
/// The card framed this as a security leak ("a field hidden from an agent leaks in Swagger"). Grounding
/// it disproved that framing: <see cref="McpIgnoreAttribute"/> is MCP-LOCAL — REST still serializes those
/// fields — so the OpenAPI document, which describes the REST contract, must KEEP them. Hiding them would
/// make the API doc claim REST returns fewer fields than it does (a new dishonesty to "fix" a non-leak).
/// Each face's schema correctly matches its OWN enforcement: MCP's <c>SchemaBuilder</c> omits [McpIgnore]
/// (see the FieldExclusion suite); OpenAPI keeps it (this suite).
///
/// What grounding DID surface is a real, different drift: the OpenAPI document is generated by
/// Microsoft.AspNetCore.OpenApi (System.Text.Json reflection) while Koan serializes REST via Newtonsoft
/// (camelCase + StringEnumConverter + [JsonProperty] renames). So the doc misrepresents the actual wire
/// for renamed fields (and enum representation). That is the genuine "one projector" gap — a
/// public-OpenAPI-contract change, flagged for an architect decision in 09 §8 / PROGRESS AN2. These specs
/// pin both the honest invariant (keep) and the current drift (characterize, until the fix lands).
/// </summary>
public sealed class SchemaProjectionConformanceSpec : IClassFixture<SwaggerWebApplicationFactory>
{
    private readonly SwaggerWebApplicationFactory _factory;

    public SchemaProjectionConformanceSpec(SwaggerWebApplicationFactory factory) => _factory = factory;

    private async Task<JObject> ProbeSchema()
    {
        using var client = _factory.CreateClient();
        var resp = await client.GetAsync("/openapi/v1.json");
        resp.StatusCode.Should().Be(HttpStatusCode.OK, "the OpenAPI document is served");
        var doc = JObject.Parse(await resp.Content.ReadAsStringAsync());
        var schema = (JObject?)doc["components"]?["schemas"]?["ProbeWidget"];
        schema.Should().NotBeNull("ProbeWidgetController references the entity, so it gets a component schema");
        return (JObject)schema!["properties"]!;
    }

    [Fact]
    public async Task OpenApi_keeps_McpIgnore_fields_because_REST_exposes_them()
    {
        var props = await ProbeSchema();
        var keys = props.Properties().Select(p => p.Name).ToList();

        keys.Should().Contain(k => string.Equals(k, "internalNote", StringComparison.OrdinalIgnoreCase),
            "REST serializes the [McpIgnore] field, so the OpenAPI doc (the REST contract) must keep it — " +
            "hiding it would make the doc lie about what REST returns");
    }

    [Fact]
    public async Task OpenApi_currently_drifts_from_the_Newtonsoft_wire_name_KNOWN_GAP()
    {
        // CHARACTERIZATION (not the desired end state): Koan serializes REST via Newtonsoft, so the field
        // Original carrying [JsonProperty("renamedField")] goes on the wire as "renamedField". The STJ-based
        // OpenAPI generator is blind to the Newtonsoft rename and emits the CLR name "original" instead —
        // the doc misnames the field. When the AN2 follow-up (a Newtonsoft-faithful OpenAPI schema
        // transformer) lands, flip this assertion. Tracked in 09 §8 / PROGRESS AN2.
        var props = await ProbeSchema();
        var keys = props.Properties().Select(p => p.Name).ToList();

        keys.Should().Contain("original",
            "current STJ OpenAPI generator ignores the Newtonsoft [JsonProperty] rename (the documented drift)");
        keys.Should().NotContain("renamedField",
            "the actual Newtonsoft wire name is not yet reflected in the OpenAPI doc (AN2 follow-up)");
    }
}

/// <summary>AN2 probe entity: a plain field, an enum, an [McpIgnore] field, and a Newtonsoft rename.</summary>
[StorageName("probe_widgets")]
public sealed class ProbeWidget : Entity<ProbeWidget>
{
    public string Name { get; set; } = "";

    public ProbeState State { get; set; }

    [McpIgnore]
    public string InternalNote { get; set; } = "";

    [JsonProperty("renamedField")]
    public string Original { get; set; } = "";
}

public enum ProbeState
{
    Draft = 0,
    Published = 1,
}

[Route("api/probe-widgets")]
public sealed class ProbeWidgetController : EntityController<ProbeWidget>
{
}
