using System.Net;
using AwesomeAssertions;
using Koan.Data.Abstractions.Annotations;
using Koan.Data.Core.Model;
using Koan.Mcp;
using Koan.Web.Controllers;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Xunit;

namespace Koan.Web.OpenApi.Tests;

/// <summary>
/// AN2 (docs/assessment/09 §8, O1ˢ) — the "one schema projector" question, empirically resolved.
///
/// The card framed this as a security leak ("a field hidden from an agent leaks in Swagger"). Grounding
/// it disproved that framing: <see cref="McpIgnoreAttribute"/> is MCP-LOCAL — REST still serializes those
/// fields — so the OpenAPI document, which describes the REST contract, must KEEP them. Hiding them would
/// make the API doc claim REST returns fewer fields than it does (a new dishonesty to "fix" a non-leak).
/// Each face's schema correctly matches its OWN enforcement: MCP's <c>SchemaBuilder</c> omits [McpIgnore]
/// (see the FieldExclusion suite); OpenAPI keeps it (this suite).
///
/// What grounding DID surface is a real, different drift: the OpenAPI document is generated by
/// Microsoft.AspNetCore.OpenApi (System.Text.Json reflection) while Koan serializes REST via Newtonsoft
/// (camelCase + StringEnumConverter + [JsonProperty] renames). So the doc misrepresented the actual wire for
/// renamed fields and emitted opaque integer enums. **FIXED (X-openapi-newtonsoft-fidelity):**
/// <c>NewtonsoftSchemaMirror</c> mirrors the Newtonsoft contract onto the STJ options the generator reads, so the
/// doc reflects the real wire names and string enums BY CONSTRUCTION. These specs now pin both the honest invariant
/// (keep [McpIgnore]) and the restored fidelity (Newtonsoft wire name + string enums).
/// </summary>
public sealed class SchemaProjectionConformanceSpec : IClassFixture<SwaggerWebApplicationFactory>
{
    private readonly SwaggerWebApplicationFactory _factory;

    public SchemaProjectionConformanceSpec(SwaggerWebApplicationFactory factory) => _factory = factory;

    private async Task<JObject> ProbeSchema()
    {
        using var client = _factory.CreateClient();
        var resp = await client.GetAsync("/openapi/v1.json");
        resp.StatusCode.Should().Be(HttpStatusCode.OK, "the OpenAPI document is served");
        var doc = JObject.Parse(await resp.Content.ReadAsStringAsync());
        var schema = (JObject?)doc["components"]?["schemas"]?["ProbeWidget"];
        schema.Should().NotBeNull("ProbeWidgetController references the entity, so it gets a component schema");
        return (JObject)schema!["properties"]!;
    }

    [Fact]
    public async Task OpenApi_keeps_McpIgnore_fields_because_REST_exposes_them()
    {
        var props = await ProbeSchema();
        var keys = props.Properties().Select(p => p.Name).ToList();

        keys.Should().Contain(k => string.Equals(k, "internalNote", StringComparison.OrdinalIgnoreCase),
            "REST serializes the [McpIgnore] field, so the OpenAPI doc (the REST contract) must keep it — " +
            "hiding it would make the doc lie about what REST returns");
    }

    [Fact]
    public async Task OpenApi_reflects_the_Newtonsoft_wire_name()
    {
        // FIXED (X-openapi-newtonsoft-fidelity): `NewtonsoftSchemaMirror` makes the STJ metadata the OpenAPI
        // generator reads mirror the Newtonsoft contract, so the field `Original` carrying
        // [JsonProperty("renamedField")] is documented as its WIRE name "renamedField" — not the CLR name.
        var props = await ProbeSchema();
        var keys = props.Properties().Select(p => p.Name).ToList();

        keys.Should().Contain("renamedField",
            "the OpenAPI doc now reflects the Newtonsoft [JsonProperty] wire name (faithful by construction)");
        keys.Should().NotContain("original",
            "the CLR name is no longer leaked into the doc");
    }

    [Fact]
    public async Task OpenApi_omits_Newtonsoft_JsonIgnore_fields()
    {
        // A Newtonsoft [JsonIgnore] field is off the wire (and storage), so the contract doc must not advertise it.
        // This is the honest way to hide a field — distinct from [McpIgnore], which only hides from the agent.
        var props = await ProbeSchema();
        var keys = props.Properties().Select(p => p.Name).ToList();

        keys.Should().NotContain(k => string.Equals(k, "secret", StringComparison.OrdinalIgnoreCase),
            "a Newtonsoft [JsonIgnore] field is absent from the REST wire, so the OpenAPI doc omits it too");
    }

    [Fact]
    public async Task OpenApi_emits_string_enums_matching_the_wire()
    {
        // API-first: enums are semantic STRING members on the wire (StringEnumConverter), so the doc must say so —
        // never opaque integers. NewtonsoftSchemaMirror adds JsonStringEnumConverter to the generator's options.
        using var client = _factory.CreateClient();
        var doc = await (await client.GetAsync("/openapi/v1.json")).Content.ReadAsStringAsync();

        doc.Should().Contain("\"Draft\"").And.Contain("\"Published\"",
            "the ProbeState enum is documented as its semantic string members, not integers");

        var props = await ProbeSchema();
        var state = props["state"] as JObject;
        state.Should().NotBeNull("ProbeWidget.State is a schema property");
        state!["type"]?.Value<string>().Should().NotBe("integer",
            "an enum property is a string in the contract, never an integer");
    }
}

/// <summary>AN2 probe entity: a plain field, an enum, an [McpIgnore] field, and a Newtonsoft rename.</summary>
[StorageName("probe_widgets")]
public sealed class ProbeWidget : Entity<ProbeWidget>
{
    public string Name { get; set; } = "";

    public ProbeState State { get; set; }

    [McpIgnore]
    public string InternalNote { get; set; } = "";

    [JsonProperty("renamedField")]
    public string Original { get; set; } = "";

    // Newtonsoft [JsonIgnore]: off the wire AND off storage — must be absent from the contract doc.
    [JsonIgnore]
    public string Secret { get; set; } = "";
}

public enum ProbeState
{
    Draft = 0,
    Published = 1,
}

[Route("api/probe-widgets")]
public sealed class ProbeWidgetController : EntityController<ProbeWidget>
{
}
