namespace Koan.Rag.Abstractions;

/// <summary>
/// An interpretation strategy that guides Round 2-3 of the multi-round extraction.
/// Can be pre-determined (shipped with framework), auto-generated (LLM-created),
/// or corpus-cached (promoted from auto-generated after repeated use).
/// </summary>
public sealed record InterpretationStrategy
{
    /// <summary>Strategy identifier (e.g., "diagram/architecture", "auto:medical-xray").</summary>
    public required string Id { get; init; }

    /// <summary>
    /// The interpretation prompt for Round 2. Tells the LLM what to extract
    /// from this specific content type.
    /// </summary>
    public required string InterpretationPrompt { get; init; }

    /// <summary>
    /// The enrichment prompt for Round 3 (optional). Extracts implicit
    /// information not covered by interpretation.
    /// </summary>
    public string? EnrichmentPrompt { get; init; }

    /// <summary>Whether Round 3 (enrichment) should run.</summary>
    public bool RequiresEnrichment { get; init; } = true;

    /// <summary>
    /// Origin of this strategy.
    /// </summary>
    public StrategyOrigin Origin { get; init; } = StrategyOrigin.PreDetermined;

    /// <summary>
    /// Number of times this strategy has been used (for corpus-cached promotion tracking).
    /// </summary>
    public int UseCount { get; init; }

    /// <summary>
    /// Content categories this strategy matches (e.g., "diagram/architecture").
    /// Slash-prefix matching: "diagram" matches "diagram/architecture" and "diagram/sequence".
    /// </summary>
    public IReadOnlyList<string> MatchCategories { get; init; } = [];
}

/// <summary>
/// Where an interpretation strategy came from.
/// </summary>
public enum StrategyOrigin
{
    /// <summary>Shipped with the framework. Optimized prompt templates.</summary>
    PreDetermined,

    /// <summary>Generated by the LLM at runtime for novel content types.</summary>
    AutoGenerated,

    /// <summary>Promoted from auto-generated after repeated use within a corpus.</summary>
    CorpusCached
}
