<#
.SYNOPSIS
  Generate docs/recipes/index.md from recipe frontmatter.

.DESCRIPTION
  The index is the one fetch an agent makes for a vague request ("what if I added AI?"). It has to be
  dense enough to reason over WITHOUT opening any recipe: what each one gets you, what must already be
  true, what it costs to operate, and what it needs. The agent composes the answer from that; nobody
  hand-writes scenario pages.

  Because it is derived, it is generated rather than maintained. -Check regenerates in memory and
  fails on drift, so a recipe edit that forgets the index cannot merge.

.EXAMPLE
  pwsh scripts/build-recipe-index.ps1
  pwsh scripts/build-recipe-index.ps1 -Check
#>
[CmdletBinding()]
param([switch]$Check)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Push-Location (Resolve-Path "$PSScriptRoot/..")
try {
    $recipeDir = 'docs/recipes'
    $indexPath = "$recipeDir/index.md"

    # A deliberately small parser for a deliberately small schema: scalars at indent 0, and lists of
    # quoted strings. Keeping the schema flat is what lets this stay dependency-free -- no YAML module
    # is guaranteed present on a build agent.
    function Read-Frontmatter([string]$Path) {
        $raw = Get-Content -Raw -LiteralPath $Path
        $m = [regex]::Match($raw, '(?s)^---\s*\r?\n(?<body>.*?)\r?\n---\s*(\r?\n|$)')
        if (-not $m.Success) { return $null }
        $data = @{}
        $currentKey = $null
        foreach ($line in ($m.Groups['body'].Value -split '\r?\n')) {
            if ($line -match '^(?<k>[A-Za-z_]+):\s*$') {
                $currentKey = $Matches['k']; $data[$currentKey] = @(); continue
            }
            if ($line -match '^(?<k>[A-Za-z_]+):\s*(?<v>.+?)\s*$') {
                $currentKey = $null
                $data[$Matches['k']] = $Matches['v'].Trim('"')
                continue
            }
            if ($currentKey -and $line -match '^\s+-\s*(?<v>.+?)\s*$') {
                $data[$currentKey] = @($data[$currentKey]) + @($Matches['v'].Trim('"'))
            }
        }
        return $data
    }

    # "one | vector index, user's choice | A, B, C" -> the middle field is what a human needs to hear.
    function Get-IngredientLabel([string]$Entry) {
        $parts = $Entry -split '\s*\|\s*'
        if ($parts.Count -lt 2) { return $Entry }
        $pick = $parts[0].Trim()
        $what = $parts[1].Trim()
        switch ($pick) {
            'optional' { "$what (optional)" }
            'one-or-more' { "$what (one or more)" }
            default { $what }
        }
    }

    $recipes = @(Get-ChildItem -LiteralPath $recipeDir -File -Filter '*.md' -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -ne 'index.md' } | Sort-Object Name)

    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine('---')
    [void]$sb.AppendLine('type: REFERENCE')
    [void]$sb.AppendLine('domain: framework')
    [void]$sb.AppendLine('title: "Koan recipes"')
    [void]$sb.AppendLine('audience: [ai-agents, developers]')
    [void]$sb.AppendLine('status: current')
    [void]$sb.AppendLine("last_updated: $(Get-Date -Format 'yyyy-MM-dd')")
    [void]$sb.AppendLine('framework_version: v1.0.0')
    [void]$sb.AppendLine('validation:')
    [void]$sb.AppendLine('  status: generated')
    [void]$sb.AppendLine('  scope: docs/recipes/index.md')
    [void]$sb.AppendLine('---')
    [void]$sb.AppendLine()
    [void]$sb.AppendLine('<!-- GENERATED by scripts/build-recipe-index.ps1 from docs/recipes/*.md frontmatter. Do not edit. -->')
    [void]$sb.AppendLine()
    [void]$sb.AppendLine('# Koan recipes')
    [void]$sb.AppendLine()
    [void]$sb.AppendLine('Each entry is something a person actually asks for. Read this page, look at the application in')
    [void]$sb.AppendLine('front of you, and compose the answer yourself — **Works if** tells you which recipes are a small')
    [void]$sb.AppendLine('step from where this application already is, and which need groundwork first. Open a recipe only')
    [void]$sb.AppendLine('once the conversation has narrowed to one.')
    [void]$sb.AppendLine()
    [void]$sb.AppendLine('A vague request is not a lookup. "I want to add AI" could be any of several of these, with')
    [void]$sb.AppendLine('different runtimes and different operational costs — offer the two or three that fit this')
    [void]$sb.AppendLine('application and say what each would cost, rather than naming a package.')
    [void]$sb.AppendLine()

    $count = 0
    foreach ($file in $recipes) {
        $fm = Read-Frontmatter $file.FullName
        if ($null -eq $fm) { continue }
        $count++
        [void]$sb.AppendLine("## $($fm['title'])")
        [void]$sb.AppendLine()
        [void]$sb.AppendLine("**Gets you** — $($fm['gets_you'])")
        [void]$sb.AppendLine()
        [void]$sb.AppendLine("**Works if** — $($fm['works_if'])")
        [void]$sb.AppendLine()
        [void]$sb.AppendLine("**Costs** — $($fm['costs'])")
        [void]$sb.AppendLine()
        if ($fm.ContainsKey('ingredients')) {
            $labels = @(@($fm['ingredients']) | ForEach-Object { Get-IngredientLabel $_ })
            [void]$sb.AppendLine("**Needs** — $($labels -join ' · ')")
            [void]$sb.AppendLine()
        }
        if ($fm.ContainsKey('absent')) {
            foreach ($a in @($fm['absent'])) {
                $parts = $a -split '\s*\|\s*'
                $what = $parts[0].Trim()
                $why = if ($parts.Count -gt 1) { $parts[1].Trim() } else { '' }
                [void]$sb.AppendLine("**Not yet** — ${what}: $why")
                [void]$sb.AppendLine()
            }
        }
        [void]$sb.AppendLine("[Open the recipe]($($file.Name))")
        [void]$sb.AppendLine()
    }

    $generated = $sb.ToString() -replace '\r\n', "`n"

    if ($Check) {
        if (-not (Test-Path -LiteralPath $indexPath -PathType Leaf)) {
            Write-Host "recipe-index: MISSING $indexPath -- run scripts/build-recipe-index.ps1" -ForegroundColor Red
            exit 1
        }
        $current = (Get-Content -Raw -LiteralPath $indexPath) -replace '\r\n', "`n"
        # last_updated moves with the clock, not with content; compare everything else.
        $strip = { param($t) ($t -split "`n" | Where-Object { $_ -notmatch '^last_updated:' }) -join "`n" }
        if ((& $strip $current) -ne (& $strip $generated)) {
            Write-Host 'recipe-index: DRIFT -- index does not match recipe frontmatter.' -ForegroundColor Red
            Write-Host '  run: pwsh scripts/build-recipe-index.ps1' -ForegroundColor Red
            exit 1
        }
        Write-Host "recipe-index: current ($count recipe(s))."
        exit 0
    }

    Set-Content -LiteralPath $indexPath -Value $generated -NoNewline -Encoding utf8
    Write-Host "recipe-index: wrote $indexPath from $count recipe(s)."
    exit 0
}
finally { Pop-Location }
